Попробовать множество стартовых точек. Чувствительность модели по нелинейным ограничениям. Определить наиболее важные показатели для ракеты.

# 7.1 ВВЕДЕНИЕ

По мере того как страна продвигалась вперед в реализации космической программы, задача разработка космических аппаратов становилась все более сложной, времязатратной и дорогостоящей. Хотя техническим проблемам и соблюдению графиков в прошлом уделялось первостепенное внимание, работа по прогнозированию и контролю затрат стала более требовательной и требует большего внимания. В результате этой тенденции требуются новые и усовершенствованные инструменты, чтобы современный менеджер мог проводить количественную оценку проблемы расчёта затрат.

Одним из инструментов, которому уделяется большое внимание и который является предметом значительных исследований, является использование моделей затрат. Модели затрат обычно используют физические характеристики системы в качестве независимых переменных, а в качестве зависимых переменных - различные затраты на систему. Использование этих моделей позволяет использовать количественный подход к решению многих проблем, связанных с расчетом стоимости.

Национальное управление по аэронавтике и исследованию космического пространства направило и провело ряд исследований по разработке моделей стоимости космических аппаратов. Большая часть этих усилий была направлена на определение моделей стоимости ракет-носителей хотя также ведется работа над моделями стоимости космических аппаратов и общей программы модели стоимости космических аппаратов. Необходимость в точных и оперативных инструментах прогнозирования стоимости стимулирует исследования во всех областях.

Большая часть работы на сегодняшний день направлена на совершенствование методов получения прогнозирования стоимости. Исследования проводились по следующим направлениям: определение параметров стоимости, разработки отношений оценки затрат (CER), и формирования описательных моделей затрат. Цель данной работы - сделать еще один шаг за пределы описательной модели затрат и разработать оптимизационную модель затрат. Для достижения этой цели достижения этой цели мы максимально использовали результаты предыдущих исследований. насколько это возможно.

------------------------------------------------------------------------

**Соотношения между затратами и оценкой** Ключевым элементом разработки предметной модели является использование CER. CER связывают конструктивные параметры и переменные ракеты-носителя с стоимостью ракеты-носителя или стоимостью конкретной подсистемы рассматриваемой ракеты-носителя. Суммирование условий CER для каждой рассматриваемой подсистемы формирует объективную функцию предметной модели.

CER, используемые в модели, были разработаны в ходе исследования затрат на компоненты ракет-носителей, проведенного компанией Lockheed Missiles and Space Company \[1\]. Определение CER осуществлялось путем сбора данных о затратах и экстраполяции, выбора конструктивных параметров и составления уравнений. Основными источниками данных были файлы данных о затратах компании Lockheed, данные NASA о Сатурне, ранее собранные данные, использованные в моделях затрат NASA, и данные других подрядчиков. Используя эту информацию, а также прогнозирование и экстраполяцию, была создана база данных для корреляционного анализа. Окончательный выбор проектных параметров и составление уравнений для оценки стоимости были выполнены с помощью корреляционного анализа. Корреляция проводилась либо с помощью компьютера, используя программу Lockheed «Программа взвешенного регрессионного анализа (WRAP), либо вручную в случае недостатка данных.

Следует признать, что CER были разработаны на основе ограниченного количества данных, а экстраполяция для передовых систем не является точным искусством. Несмотря на эти ограничения, необходимо, чтобы CER формировались с опорой на лучшие имеющиеся данные для планирования передовых систем.

Необходимость в более точных CER является требованием ко всем моделям затрат. CER были разработаны различными подрядчиками и агентствами, но дальнейшая работа все еще необходима.

**Вводное обсуждение модели оптимизации с ограничениями** Для того чтобы модель была представлена в как можно более реалистичном виде, в качестве основы используется пример ракеты-носителя. В качестве примера используется трехступенчатая ракета-носитель, типичная для орбитальной или околоземной миссии. Подробное описание примера ракеты-носителя приведено в разделе 7.2. Однако следует отметить, что модель не ограничивается примером ракеты-носителя, и что целевая функция и ограничения могут быть изменены, чтобы приспособиться к любому типу ракеты, для которой можно определить CER.

Несмотря на то, что используется пример ракеты-носителя, мы стремимся к тому, чтобы модель имела как можно более обобщенный формат и проиллюстрировать метод для разработки моделей для всех типов ракет-носителей. В общем случае целевая функция - это функция затрат, которую необходимо минимизировать. Функция затрат выражается через CER как функция переменных, определяющих общую стоимость

------------------------------------------------------------------------

разработки, строительства и запуска ракеты-носителя. Ограничения основаны на желаемых характеристиках ракеты-носителя. Типичный вид общего ограничения заключается в том, что ракета-носитель должна доводить заданную полезную нагрузку (PL) до определенной скорости. Именно этот тип общего ограничения использовался для модели и разработан в разделе 7.3. Для разработки всех ограничений которые выражают требуемые физические характеристики системы, задается ряд нелинейных и линейных зависимостей.

Модель, разработанная для примера ракеты-носителя, решается методом последовательной минимизации без ограничений. Результаты приведены в Разделе 7.4.

Данный тип модели предназначен в первую очередь для использования группами, занимающимися будущими проектами и предварительным планированием ракет-носителей. Она представляет собой начальную попытку получить валидный и гибкий инструмент, который специалисты по перспективному планированию могут использовать на начальных этапах проектирования для получения оптимальных проектных параметров. Эти параметры выбираются для получения минимальной общей стоимости ракеты-носителя в рамках ограничений на характеристики необходимых для выполнения миссии. Если бы модель была разработана до дальнейшего уровня сложности, необходимо было бы сделать конкретное определение ее применение. Два самых разных примера применения - использование для получения детальных параметров проектирования и использование исключительно в качестве руководства для предварительного планирования.

# 7.2 РАЗРАБОТКА ФУНКЦИИ ЗАТРАТ

**Определение переменных** Общая стоимость разработки, строительства и запуска ракеты-носителя должны быть выражены как функция переменных конструкции. Рассматриваются только затраты на ракету-носитель, а разработка полной функции стоимости космического аппарата включая космический аппарат или другие PL, не рассматривается. В данной модели ракета-носитель определяется как совокупность трех разгонных ступеней и приборного блока. Приборный блок представляет собой систему наведения и управления для всех трех ступеней. PL или космический корабль - это тот пакет над ракетой-носителем, который ракета-носитель должна вывести на желаемую орбиту или космическую траекторию. Космический аппарат определяется как совокупность ракеты-носителя и космического аппарата или PL. Функция затрат, выражающая стоимость всей программы разработки и производства ракеты-носителя является целевой функцией оптимизационной модели затрат.

При построении модели затрат в качестве примера используется типичная ракета-носитель. Перед разработкой модели необходимо сделать ряд базовых проектных допущений. Эти допущения включают в себя количество ступеней в ракете-носителе, количество двигателей на ступень, тип ракетного топлива, и общее количество ракет-носителей, которые будут построены.

------------------------------------------------------------------------

При рассмотрении уравнений ограничений делаются дополнительные предположения, но упомянутые имеют первостепенное значение для функции стоимости.

Для наглядности в качестве примера приведена трехступенчатая ракета-носитель. Первая ступень имеет пять одинаковых двигателей с колоколообразным типом выхлопной камеры. В двигателях первой ступени используется жидкий кислород/ракетный снаряд (LOX/RP) топливо. Вторая ступень также имеет пять двигателей колоколообразного типа. Двигатели второй ступени также используют топливо LOX/RP, однако предполагается, что их конструкция и тяга будут отличаться от двигателей первой ступени. Третья ступень имеет один колоколообразный двигатель. Двигатель третьей ступени использует топливо на основе жидкого кислорода/жидкого водорода (LOX/$LH_2$). Рассматривается ступень приборного блока, которая содержит системы наведения и управления отдельных ступеней. В функции затрат PL не учитывается, хотя она присутствует в уравнениях ограничений. Таким образом, модель предназначена исключительно для стоимости ракеты-носителя. Количество ракет-носителей, которые необходимо построить и запустить обозначается как константа $K_1$.

Основные затраты на программу создания ракет-носителей приходятся на три основные области: научно-исследовательские и опытно-конструкторские работы (R&D), производство оборудования и эксплуатация ракет-носителей. Стоимость объектов для производства и запуска, которая может стать четвертой основной статьей расходов, не рассматривается, и предполагается использование существующих объектов. Затраты на (R&D) и аппаратуру определяются на уровне подсистем для каждой ступени и на уровне системы для приборного блока. Стоимость пусковых операций определяется по уравнению, представляющему запуск всей ракеты-носителя.

Две основные подсистемы, входящие в состав каждой ступени, - это планер и двигательная установка. Другие подсистемы менее значимые с точки зрения общей стоимости ступени, не рассматриваются. Предполагается, что две рассматриваемые подсистемы представляют весь этап. Уравнения, отражающие стоимость двух подсистем, в основном выражают в переменных веса и/или тяги. CER между данными переменными и стоимостью выражаются уравнениями для различных категорий стоимости планера и силовой установки.

При разработке модели затрат переменные определяются следующим образом:

-   $X_{11}$ = вес планера этапа 1 (тыс. фунтов),

-   $X_{12}$ = общая инертная масса этапа 1 (тыс. фунтов),

-   $X_{13}$ = массовая доля этапа 1 (безразмерная),

-   $X_{14}$ = общая тяга ступени 1 (тысячи фунтов),

-   $X_{15}$ = масса импульсного топлива ступени 1 (тысячи фунтов),

-   $X_{16}$ = тяга отдельных двигателей ступени 1 (тысячи фунтов),

-   $X_{17}$ = длина ступени 1 (футы),

-   $X_{21}$ = вес планера ступени 2 (тысячи фунтов),

-   $X_{22}$ = общий инертный вес ступени 2 (тысячи фунтов),

------------------------------------------------------------------------

-   $X_{23}$ = массовая доля ступени 2 (безразмерная),

-   $X_{24}$ = общая тяга ступени 2 (тысячи фунтов),

-   $X_{25}$ = масса импульсного топлива ступени 2 (тыс. фунтов),

-   $X_{26}$ = тяга двигателя ступени 2 (тысячи фунтов),

-   $X_{27}$ = длина Stage 2 (футы),

    ------------------------------------------------------------------------

-   $X_{31}$ = вес планера ступени 3 (тысячи фунтов),

-   $X_{32}$ = общая инертная масса Stage 3 (тысячи фунтов),

-   $X_{33}$ = массовая доля ступени 3 (безразмерная),

-   $X_{34}$ = общая тяга ступени 3 (тысячи фунтов),

-   $X_{35}$ = масса ракетного топлива ступени 3 (тысячи фунтов),

-   $X_{36}$ = тяга импульсного двигателя ступени 3 (тысячи фунтов),

-   $X_{37}$ = длина ступени 3 (футы),

-   $X_{41}$ = вес приборной части (тысячи фунтов),

```         
------------------------------------------------------------------------
```

-   $t_{1}$ = время горения ступени 1 (секунды),

-   $t_{2}$ = время сгорания ступени 2 (секунды),

-   $t_{3}$ = время сгорания ступени 3 (секунды).

**Общие затраты на (R&D) и производство на этапе 1**

Переменные, которые необходимо использовать для определения функции затрат на этапе 1, определены выше. Эта часть функции затрат, охватывающая как расходы на (R&D) и производственные затраты, разрабатывается в условиях планера и двигательной подсистемы. Проектные допущения этапа 1 будут такими, как указано в предыдущем описании примера ракеты-носителя.

**Стоимость (R&D) планера на этапе 1**

Первая категория затрат, которую необходимо учитывать на этапе 1, - это стоимость (R&D) планера. Эта категория затрат представляет собой комбинацию затрат на проектирование и разработку планера проектирование, оснастку, специальное испытательное оборудование, оборудование для испытаний подсистем и оборудования для статических испытаний, а также затрат на поддержку и приемку подсистем и статических испытаний. поддержки и приемки испытаний подсистем и статических испытаний. Уравнение для общей стоимости (R&D) планера, взятое из исследования компании Lockheed:

$$Y = 5272.77*(X_{11})^{(1.2781)}*(X_{12})^{(-0.1959)}*(X_{13})^{(2.4242)}*(X_{14})^{(0.38745)}*(X_{15})^{(-0.9904)}$$

Член Y равен общей стоимости (R&D) планера 1-го этапа в миллионах долларов. Уравнение учитывает три основных конструктивных параметра планера - вес ($X_{11}$, $X_{12}$ и $X_{15}$), тягу ($X_{14}$) и массовую долю ($X_{13}$) - и применимо к расходуемым химическим летательным аппаратам. Подробное определение термина «массовая доля» приведено в разделе 7.3. В этом разделе также рассматриваются взаимосвязи между переменными. Что касается переменной массы ракетного топлива, $X_{15}$, то следует отметить, что импульсный вес топлива равен общему весу топлива, и никаких остатков после сгорания не предполагается.

------------------------------------------------------------------------

Стоимость (R&D) двигателя на этапе 1 Следующей стоимостью, которую необходимо рассмотреть, является стоимость (R&D) двигательной подсистемы. Эта категория затрат включает в себя инженерно-конструкторские разработки, испытательное оборудование, специальное испытательное оборудование, квалификационные испытания и затраты на ракетное топливо. Уравнение для суммарных затрат на (R&D) по этапу 1 для двигателя, проходящего квалификацию, взятое из исследования Lockheed, выглядит следующим образом

$$Y = -247.963 + 160.909 * (\dfrac{X_{16}}{10^3})^{-0.146} + 282.874 * (\dfrac{X_{16}}{10^3})^{0.648}$$

В этом уравнении Y равно общей стоимости (R&D) двигателя этапа 1 через квалификации в миллионах долларов. Уравнение приведено для конкретного примера Этапа 1, то есть двигателя, сжигающего LOX/RP с колоколообразным соплом. Если бы двигатель использовал другой тип топлива, константы в приведенном выше уравнении были бы изменены, как это сделано в случае двигателя Стадии 3. Если используется сопло другого типа или ядерный или воздушно-дыхательный двигатель, необходимо определить новое уравнение. Первая ступень зажигается на поверхности Земли, поэтому для двигателя тяга на уровне моря используется для переменной тяги двигателя $X_{16}$. Как и в случае для ступеней 2 и 3, тяга двигателя используется для всех верхних ступеней.

**Стоимость производства воздушного каркаса стадии 1** Первой подсистемой, которую необходимо рассмотреть для получения стоимости производства на этапе 1 является планер. Основное уравнение для стоимости производства планера приведено в терминах стоимости первой производственной единицы и взято из исследования Lockheed. Планер, как определено здесь, включает в себя конструктивные баки, изоляцию, тяговую конструкцию, обтекатели, вспомогательное оборудование двигателя, топливные системы, систему окислителя, органы управления ступенью, телеметрическую структуру, пневматическую систему, систему разделения, и промежуточную ступень (та часть, которая присоединяется к ступени при отделении). Чтобы получить общую стоимость производства всех подсистем планера, произведенных для этапа 1, количество произведенных изделий возводится в определенную степень, зависящую от наклона кривой обучения, и умножается на базовое уравнение для первой производственной единицы. Это приближение обычно используется для кривых обучения. Все используемые значения кривой обучения взяты из исследования Lockheed, вместе с применимыми терминами стоимости. Предполагается, что количество произведенных планеров равно количеству требуемых ступеней и, следовательно, равно количеству ракет-носителей, которые необходимо построить и запустить, $K_1$. Стоимость производства первой единицы планера для первой ступени в долларах составляет

$$Y = 185.214*(X_{11})^{(0.3322)}*(X_{13})^{(-1.5935)}*(X_{15})^{(0.2362)}*(X_{17})^{(0.1079)}*(K_{2})^{(0.1616)}$$ где $K_2$ = количество двигателей для этапа 1 = 5.

------------------------------------------------------------------------

Общая стоимость производства планера для этапа 1, в миллионах долларов, составляет $$Y = 185.214*(X_{11})^{0.3322}*(X_{13})^{-1.5935}*(X_{15})^{0.2362}*(X_{17})^{0.1079}*(5)^{0.1616}*{(K_1)}^{\gamma}*({10^{-6}})$$, где $\gamma$ = наклон кривой обучения = 0,90.

**Стоимость производства двигателя 1-го этапа** Стоимость аппаратного обеспечения двигательной подсистемы является следующей, которую необходимо рассмотреть и, как и в случае с затратами на производство планера, определяется стоимость первой производственной единицы. Уравнение стоимости первой производственной единицы в миллионах долларов для двигателя Stage 1 LOX/RP с колоколообразным соплом, взятое из исследования компании Lockheed, выглядит следующим образом: $$Y = 0.2085 * (\dfrac{X_{16}}{10^3}) + 2.509 * (\dfrac{X_{16}}{10^3})^{0.736} + 0.9744 * (\dfrac{X_{16}}{10^3})^{-0.229}$$ Общая стоимость производства двигателей Этапа 1, в миллионах долларов: $$Y =[ 0.2085*{(\dfrac{X_{16}}{10^3}})+ 2.509*{(\dfrac{X_{16}}{10^3}})^{0.736} +0.9744*{(\dfrac{X_{16}}{10^3}}))^{-0.229} ]* (5K_1)^{0.93}$$ Член $5K_1^ \gamma$ - это общее количество произведенных двигателей, возведенное в степень наклона кривой обучения. Для данного двигателя наклон кривой обучения равен 0,93. Уравнение относится к общей стоимости производства оборудования, исключая запасные части.

**Общие затраты на (R&D) и производство на этапах 2 и 3** Функции затрат на этапах 2 и 3 разрабатываются так же, как и функции затрат на этапе 1. Используются те же подсистемы, а переменные и проектные допущения определены ранее в этом разделе для примера транспортного средства. Поскольку проектные допущения для этапа 2 по топливу и количеству двигателей двигателей такие же, как и для этапа 1, включение переменных этапа 2 является единственным изменением в функции затрат для этапа 2. В связи с этим нет необходимости повторять обсуждение разработки функции затрат для этапа 2. Функция затрат для этапа 3, хотя и разработана таким же образом, имеет несколько иные значения из-за использования топлива LOX/$LH_2$ и только одного двигателя. Это в первую очередь влияет на стоимость двигателя. Стоимость планера отличается только за счет включения переменных Этапа 3 и значения 1 для числа двигателей в стоимости производства планера. Из-за разницы в топливе, рассматриваются затраты на (R&D) и производство двигателей Стадии 3 обсуждается.

------------------------------------------------------------------------

**Стоимость (R&D) двигателя 3 этапа** Стоимость (R&D) двигателя для этапа 3 определяется по тому же базовому уравнению, что и для этапов 1 и 2. Константы уравнения изменены в связи с изменением топлива с LOX/RP на LOX/$LH_2$ на этапе 3. Общая стоимость (R&D) до момента квалификации для двигателя этапа 3, в миллионах долларов, составляет

$$Y = 32.591 * 181.806(\dfrac{X_{36}}{10^3})^{0.539} + 232.57 * (\dfrac{X_{36}}{10^3})^{0.772}$$

Это уравнение для двигателя LOX/$LH_2$ взято из исследования Lockheed. Комментарии по стоимости (R&D) двигателя для этапа 1 применимы.

**Стоимость производства двигателя для этапа 3** Стоимость производства двигателя для этапа 3 определяется из того же базового уравнения, что и для этапов 1 и 2. Константы уравнения изменены чтобы учесть топливо LOX/$LH_2$ для этапа 3. Стоимость первой производственной единицы двигателя этапа 3, в долларах, составляет

$$Y = [0.0705 * (\dfrac{X_{36}}{10^2}) - 0.1807 * (\dfrac{X_{36}}{10^2})^{-1.33} + 166.87 * (\dfrac{X_{36}}{10^2})^{0.498}]*(10^5)$$

Общая стоимость производства двигателей этапа 3, в миллионах долларов, составляет $$Y = [0.0705 * (\dfrac{X_{36}}{10^2}) - 0.1807 * (\dfrac{X_{36}}{10^2})^{-1.33} + 166.87 * (\dfrac{X_{36}}{10^2})^{0.498}]*(10^{-1})(K_1)^{0.93}$$ Комментарии к стоимости производства двигателя 1-го этапа применимы и к стоимости производства двигателя 3-го этапа. Приведенное выше уравнение для стоимости производства единицы продукции было взято из исследования Lockheed и относится только к двигателям LOX/$LH_2$. На этом затраты на Стадию 3 и развитие по стадиям (R&D) и аппаратных затрат заканчиваются. Стоимость приборного блока, который не рассматривается как этап, определяется примерно таким же образом в следующем подразделе

**Стоимость приборного блока ракеты-носителя** Наведение и управление ракетой-носителем осуществляется всеми тремя ступенями от одного приборного блока на протяжении всего полета. Приборный блок установлен на верхней части третьей ступени и под PL. Таким образом, 1 фунт веса приборного блока эквивалентен 1 фунту веса PL с точки зрения характеристик ракеты-носителя. Стоимость определяется по уравнениям (R&D) и производства, как это было сделано для каждой ступени.

**Стоимость (R&D) приборного блока** Стоимость (R&D) приборного блока определяется уравнением, представляющим общие затраты на (R&D) системы наведения и управления. Эта категория затрат включает в себя инженерно-конструкторские разработки, оснастку, специальное испытательное оборудование, компоненты, испытательное оборудование и интеграцию компонентов. Уравнение для стоимости (R&D) системы наведения и управления, взятое из исследования Lockheed, выглядит следующим образом $$Y = 10.35 \{15.822[(X_{41})(10^3)]^{0.736}*(10^{-6})\} - 35.5.$$ Переменная $X_{41}$ - это вес приборного блока в тысячах фунтов. В уравнение не включены аппаратные блоки для летных испытаний. Стоимость летно-испытательных блоков может быть определена с помощью стоимости одного блока, которая представляет собой заключенную в скобки часть уравнения (R&D), приведенного выше. Для целей примера предполагается, что любые летные испытания приборного блока будут включать в себя всю ракету-носитель. Поэтому стоимость оборудования для летных испытаний может рассматриваться как стоимость производственного оборудования и не требует добавления в уравнение затрат на (R&D). Приведенное выше уравнение представляет собой общую стоимость (R&D) приборного блока в миллионах долларов.

**Стоимость производства приборного блока** Стоимость производства системы наведения и управления является последней стоимостью аппаратуры, которую необходимо рассмотреть. Уравнение для стоимости первого производства приборного блока в долларах, взятое из исследования компании Lockheed, выглядит следующим образом $$ Y= 15.822[(X_{41})(10^3)]^{0.786}.$$ Общая стоимость производства приборного блока для всех первых ступеней, в миллионах долларов, составляет $$ Y = \{ 15.822[(X_{41})(10^3)]^{0.786} \} (10^{-6})(K_1)^\gamma.$$

Для данного уравнения и примера наклон кривой обучения $\gamma$ равен 0.90. Общее оборудование приборного блока включает в себя компьютер, адаптер, платформу, управление полетом и прочее оборудование. На этом мы завершаем разработку (R&D) и стоимости оборудования для примера ракеты-носителя.

**Эксплуатационные расходы ракеты-носителя** Последней крупной областью расходов, которую необходимо рассмотреть, является стоимость эксплуатации ракеты-носителя. Эта стоимость определяется по уравнению, разработанному для всей ракеты-носителя, а не для ступеней и подсистем. Стоимость эксплуатации включает в себя расходы на эксплуатацию площадки, топливо, транспортировку и прочую операционную поддержку. Уравнение для этой функции, взятое из исследования компании Lockheed \[1\]:

$$Y = 8.5 [\dfrac{(X_{15} + X_{25} + X_{35})(C)^{0.460}}{1000}](K_1),$$

где C = количество ступеней = 3. Это уравнение дает общую стоимость полета для всех запущенных аппаратов $(K_1)$, в миллионах долларов.

**Функция общей стоимости** Общая стоимость программы запуска ракеты-носителя представляет собой сумму всех затрат, описанных в данном разделе. Общая стоимость, которая является объективной функцией модели затрат может быть представлена в виде

Общая стоимость = стоимость (R&D) + стоимость оборудования + эксплуатационные расходы.

Первые два элемента общей стоимости, стоимость (R&D) и стоимость оборудования, были разработаны по отдельным этапам и приборным блокам.

Затраты на первом этапе составляют (R&D) планера + (R&D) силовой установки LOX/RP + единица производства планера $(K_1)$ + единица производства LOX/RP двигателя (5) $(K_1)$.

**Затраты второго этапа составляют** (R&D) планера + (R&D) силовой установки LOX/RP + единица производства планера $(K_1)$ + LOX/RP единица производства двигателя (5) $(K_1)$.

**Затраты третьего этапа составляют** (R&D) планера + (R&D) силовой установки LOX/$LH_2$ + единица производства планера $(K_1)$ + единица производства двигателя LOX/$LH_2$ (1) $(K_1)$.

**Затраты на приборный блок составляют** (R&D) приборного блока + производство приборного блока $(K_1)$.

**Эксплуатационные расходы на ракету-носитель составляют** Эксплуатационные расходы на запуск $(K_1)$.

Таким образом, полная объективная функция модели, которую необходимо минимизировать, выглядит следующим образом. Этап 1 $$[5272.77(X_{11})^{1.2781}(X_{12})^{-0.1959}(X_{13})^{2.4242}(X_{14})^{0.38745}(X_{15})^{-0.9904}] + [-247.963 + 160.909 (\dfrac{X_{16}}{10^{3}})^{-0.146} + 282.874(\dfrac{X_{16}}{10^{3}})^{0.648}]+[185.214(X_{11})^{0.3322}(X_{13})^{-1.5935}(X_{15})^{0.2363}(X_{17})^{0.1079}(5)^{0.1616}(K_1)^{0.9}(10)^{-6}] + [0.2085(\dfrac{X_{16}}{10^{3}}) + 2.509(\dfrac{X_{16}}{10^{3}})^{0.736} + 0.9744(\dfrac{X_{16}}{10^{3}})^{-0.229}](5K_1)^{0.93}$$

------------------------------------------------------------------------

Этап 2 $$+[5272.77(X_{21})^{1.2781}(X_{22})^{-0.1959}(X_{23})^{2.4242}(X_{24})^{0.38745}(X_{25})^{-0.9904}] + [-247.963 + 160.909 (\dfrac{X_{26}}{10^{3}})^{-0.146} + 282.874(\dfrac{X_{26}}{10^{3}})^{0.648}]+[185.214(X_{21})^{0.3322}(X_{23})^{-1.5935}(X_{25})^{0.2363}(X_{27})^{0.1079}(5)^{0.1616}(K_1)^{0.9}(10)^{-6}] + [0.2085(\dfrac{X_{26}}{10^{3}}) + 2.509(\dfrac{X_{26}}{10^{3}})^{0.736} + 0.9744(\dfrac{X_{26}}{10^{3}})^{-0.229}](5K_1)^{0.93}$$

Этап 3 $$+[5272.77(X_{31})^{1.2781}(X_{32})^{-0.1959}(X_{33})^{2.4242}(X_{34})^{0.38745}(X_{35})^{-0.9904}] + [32.591 + 181.806 (\dfrac{X_{36}}{10^{3}})^{0.539} + 232.57(\dfrac{X_{36}}{10^{3}})^{0.772}]+[185.214(X_{31})^{0.3322}(X_{33})^{-1.5935}(X_{35})^{0.2363}(X_{37})^{0.1079}(1)^{0.1616}(K_1)^{0.90}(10)^{-6}] + [0.0705(\dfrac{X_{36}}{10^{2}}) - 0.1807(\dfrac{X_{36}}{10^{2}})^{-1.33} + 166.87(\dfrac{X_{36}}{10^{2}})^{0.498}](10)^{-1}(K_1)^{0.93}$$

Приборная установка $$+\{{10.35[15.822(X_{41} * 10^3)^{0.786}(10)^{-6}] - 35.5} \}+ [15.822(X_{41} * 10^3)^{0.786}(10)^{-6}(K_1)^{0.90}]$$ Пусковые операции $$+8.5[\dfrac{(X_{15}+X_{25}+X_{35})(3)}{1000}]^{0.460}(K_1).$$

Следует отметить, что в четвертом члене затрат этапа 3 появляется коэффцииент 166.87. В наших численных решениях, рассмотренных в разделе 7.4 мы ошибочно использовали коэффициент 16,687.

\### 7.3 РАЗРАБОТКА ОГРАНИЧЕНИЙ

**Определение типов ограничений** Цель ограничений в модели - определить основные условия задачи и ограничения на каждую из переменных. Условия и ограничения на данные переменные определяются тремя наборами взаимосвязей. Определяющие взаимосвязи семи переменных каждого этапа определяются определением переменных. Основные взаимосвязи характеристик определяются фундаментальными научными законами и определениями ракетного движения.

Третья группа отношений - это отношения, установленные для выражения желаемых параметров работы. В этом разделе выражаются равенства или неравенства необходимые ограничения из каждого из трех базовых отношений для каждой из трех ступеней и для инструментального блока примера модели.

**Общие ограничения стадии 1** Ограничения этапа 1 разрабатываются на основе трех основных типов отношений, упомянутых выше. Подробно это сделано для этапа 1. При разработке уравнений ограничений предполагается, что основные проектные допущения, использованные при разработке целевой функции, сохраняются и в данной модели. Необходимые дополнительные допущения обсуждаются по мере разработки ограничений.

**Этап 1 Взаимосвязь определений** Взаимосвязь определений возникает в результате определений, которые позволяют выразить одни переменные в терминах других переменных в рамках базового набора из семи переменных этапа 1, которые фигурируют в функции цели. Благодаря этим взаимосвязям определений можно сократить количество переменных, используемых в постановке задачи. Этого можно добиться, используя взаимосвязи определений и исключая те переменные, которые можно выразить в терминах других переменных. Однако нежелательно устранять лишние переменные, поскольку это вносит дополнительную ясность при изменении взаимосвязей от задачи к задаче, а также благодаря краткости, достигаемой за счет использования дополнительного термина переменной. Первая дефинитивная взаимосвязь этапа 1 - это определение весов. Уравнение имеет вид $$(0.5)X_{12}=X_{11}$$

Это уравнение показывает, что вес планера равен половине общего инертного веса ступени 1. Другая половина общего веса пустой ступени приходится на двигательную подсистему и оборудование других подсистем, например, приборы. Двигательная подсистема составляет большую часть оставшейся половины, а различное оборудование - гораздо меньшую часть. Использование половины в качестве доли планера от общего веса пустой ступени является произвольным суждением, основанным на значениях, полученных на аналогичных ступенях. Кривая, изображающая это дробное значение, может быть построена на основе количества двигателей и относительного размера планера. Однако для наших целей это нецелесообразно. Для определения значений для этапов 2 и 3 снова будет использоваться произвольное суждение, основанное на опыте.

Второе определение - это взаимосвязь между тягой этапа и тягой одного двигателя. Это уравнение для первой ступени с пятью двигателями показывает, что тяга ступени равна тяге одного двигателя, умноженной на количество двигателей. Уравнение выражается следующим образом $$X_{14}=(5)X_{16}.$$ Число двигателей, а именно пять для ступени 1, является основным допущением при проектировании приведенное в разделе 7.2. Следующей определяющей взаимосвязью является безразмерная величина - массовая доля ступени. Для этапа 1 этот важный параметр при проектировании планера - это отношение массы ракеты-носителя после сгорания ступени 1 и до отделения ступени 1 к начальной массе ракеты-носителя. В форме уравнения это выражается следующим образом

$$X_{13}=\dfrac{X_{12}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}{X_{12}+X_{15}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}$$

Подробнее о массовой доле ступени будет рассказано в разделе «Основные параметры работы». Для сохранения целостности конструкции необходимо обеспечить соотношение между инертной массой ступени и массой ракетного топлива. Это соотношение имеет вид $$12X_{12} \leq X_{15}\leq16X_{12}$$ Из этих двух неравенств следует, что масса ракетного топлива для 1-й ступени в 12 и 16 раз больше веса инертного топлива для 1-й ступени. Диапазон от 12 до 16 был выбран произвольно на основе конструкции аналогичных ступеней. Таким образом, размер ступени и количество вмещаемого ею топлива коррелируют. Последней переменной, которую необходимо рассмотреть для ступени 1, является длина ступени, $X_{17}$. Определенная зависимость между длиной ступени и массой инертной ступени или массой ракетного топлива, вероятно, может быть определена с помощью ограничений по объему и плотности. Однако представляется наиболее целесообразным позволить этой переменной колебаться между произвольными пределами, установленными из-за возможности управления или практичности конструкции. $$C^l_{17} \leq X_{17} \leq {C^\mu_{17}}.$$ Границы $C^l_{17}$ и $C^{\mu}_{17}$ определяются путем выбора значений на основе знания типичных видов ступеней, необходимых для удовлетворения требований к производительности. Таким образом, границы $$125 \leq X_{17} \leq 150.$$ Это завершает определение взаимосвязей стадии 1

**Этап 1 Основные отношения производительности** Основные соотношения характеристик - это, по сути, определение основных соотношений параметров характеристик, используемых в ракетах. Эти основные рабочие параметры выражаются в терминах переменных модели примера. Параметры, которые мы будем обсуждать, - это наиболее важные рабочие параметры, используемые в ракетах. Одним из наиболее важных параметров является удельный импульс, $I_s$. Его можно определить как «импульс, приходящийся на единицу массы ракетного топлива». Уравнение для удельного импульса в переменных модели имеет вид $$I_s=\dfrac{F}{W}=\dfrac{(X_{14})(t_1)}{X_{15}}.$$В измерениях удельный импульс - это фунт тяги, деленный на фунт в секунду расхода ракетного топлива. Таким образом, приведенное выше уравнение дает тягу, деленную на расход ракетного топлива. Для топлива LOX/RP, используемого на этапе 1, удельный импульс может принимать различные значения из-за давления в камере, соотношения смеси, давления и скорости на выходе и других факторов. Для удельного импульса двигателей 1-й ступени даны границы, соответствующие типу топлива и желаемым характеристикам. Таким образом, уравнение удельного импульса переписывается в виде ограничений следующим образом: $$240=\dfrac{(X_{4})(t_1)}{X_{15}}\leq290.$$ Следующий параметр производительности, который необходимо обсудить, - это массовая доля ступени, $X_{13}$. Этот расчетный параметр, являющийся переменной в модели, представляет собой отношение конечной массы аппарата после сгорания топлива на первой ступени к начальному весу аппарата, включая топливо. Для первой ступени он выражается следующим образом $$SMF_1=\dfrac{M_f}{M_0}=X_{13}.$$

При разработке ограничений этой модели разница между начальным и конечным весом принимается за общий вес ракетного топлива. При этом предполагается, что все топливо сгорает и остатков не остается. Это сделано для упрощения модели и не оказывает большого влияния на точность, так как остаток составляет очень малый процент от общего количества топлива. Если бы требовалась большая точность, остатки можно было бы включить в модель. Массовая доля является важным параметром производительности поскольку она оказывает значительное влияние на достижимую скорость ступени. Это видно из последующих уравнений в следующем подразделе, где используется массовая доля. Переменная $X_{13}$ ограничена типичными значениями, достижимыми при хорошей конструкции ступени и необходимыми для требуемых в модели характеристик. Таким образом ограничение на массовую долю ступени 1: $$0.25 \leq X_{13} \leq 0.30.$$

------------------------------------------------------------------------

Отношение тяги к начальному весу ступени - следующий параметр эффективности, который необходимо рассмотреть. Это отношение не требует пояснений и выражается следующим образом

$$\dfrac{F}{W_0}=\dfrac{X_{14}}{X_{12}+X_{15}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}.$$

Тяга - это суммарная тяга ступени $X_{14}$, а вес - это начальный вес ракеты-носителя плюс ракетное топливо и PL. Границы, установленные для этого параметра являются типичными для состояний, необходимых в диапазоне характеристик модели. Таким образом ограничения на отношение тяги к весу $$1.2 \leq \dfrac{X_{14}}{{X_{12}+X_{15}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}} \leq 1.4.$$ На этом мы завершаем подраздел основных зависимостей характеристик

**Этап 1 Взаимосвязи параметров желаемой производительности**

Зависимости параметров желаемых характеристик определяются из основных уравнений движения и связывают скорость и высоту с заданными переменными. Здесь рассматривается только скорость, и уравнение относится к упрощенной вертикальной траектории с дополнительными допущениями, упрощающими модель. Уравнение было выбрано из-за его простоты и предназначено для иллюстрации включения переменных в уравнения характеристик. Более сложные уравнения, используемые для детального проектирования, также могут быть адаптированы для использования с переменными, заданными в функции цели. Влияние принятых допущений рассматривается в этом подразделе и в подразделе «Общие ограничения ракеты-носителя». Желаемым параметром эффективности для упрощенной вертикальной траектории является скорость, которая может быть достигнута для вертикально поднимающейся ракеты при условии, что что а) Земля неподвижна, b) направление тяги совпадает с траекторией полета, и c) отсутствуют боковые силы. Эти предположения в основном означают, что влияние центробежных сил и сил Кориолиса, а также влиянием аэродинамических боковых нагрузок пренебрегается. Эти эффекты имеют относительно небольшую величину. По определению траектории, маневрирование ракеты-носителя на этапе разгона не требуется. В соответствии с вышеизложенными предположениями, скорость всего аппарата по окончании времени горения 1-й ступени, $t_1$, определяется следующим образом

$$v_1=\overline{c} \ln(\dfrac{M_0}{M_f}) - \overline{g}t_1 - \dfrac{B_1C_DA}{W_0} + v_0$$

Если рассматривать условия этого уравнения от последнего к первому, то начальная скорость $v_0$ при зажигании двигателей первой ступени принимается равной нулю, что означает запуск с площадки.

------------------------------------------------------------------------

Следующий член, $(B_1C_DA)/W_0$, представляет собой эффект земной атмосферы. Этот член аэродинамического сопротивления состоит из коэффициента сопротивления, $C_D$, для ракеты-носителя, максимальной площади поперечного сечения A ракеты-носителя, начального веса $W_0$ ракеты-носителя перед запуском, и члена $B_1$. Член $B_1$ представлен следующим интегралом:

$$B_1=g_0\int_{0}^{t_1}\dfrac{\dfrac{1}{2}pv^2}{1-\dfrac{\alpha t}{t_1}}dt.$$ В этой модели аэродинамическое сопротивление не учитывается, и поэтому скорость 1 ступени будет больше той, которая будет достигнута в действительности. Для большой, хорошо спроектированной ракеты-носителя штраф в скорости выгорания из-за атмосферного сопротивления составляет менее 2 процентов. Таким образом, это исключение не имеет большого значения. Следующий член, $\overline g t_1$, представляет собой эффект гравитации в течение времени выгорания, $t_1$. Этот член не будет учитываться в расчетах скорости, поэтому уравнение для скорости игнорирует все внешние силы и сводится к тому, что можно назвать «идеальной скоростью». Чтобы компенсировать исключение внешних сил, общее ограничение скорости будет выражено в условиях идеальной скорости для миссии. Это обсуждается далее в последней части данного раздела. Оставшийся член уравнения скорости для ступени 1 представляет собой скорость, придаваемую массе в течение времени горения $t_1$, при идеализированных условиях, рассмотренных выше. Таким образом, уравнение скорости для ступени 1: $$v_1=\overline{c} \ln (\dfrac{M_0}{M_f}),$$ где $M_0$ и $M_f$ - соответственно начальная масса всей ракеты-носителя и конечная масса после сгорания 1-й ступени. Эффективная скорость выхлопа, $\overline c$, определяется как удельный импульс, $I_S$, умноженный на среднюю силу тяжести, $\overline g$. Отношение $M_0/M_f$ является обратной величиной к массовой доле ступени. Таким образом, при подстановке ранее определенных выражений для эффективной скорости выхлопа и массовой доли уравнение скорости в терминах переменных модели имеет вид

$$v_1=\dfrac{X_{14}t_1\overline{g}}{X_{15}} \ln (\dfrac {1}{X_{13}})$$

**Общие ограничения этапов 2 и 3**

Ограничения этапов 2 и 3 разрабатываются так же, как и ограничения этапа 1. Разрабатываются те же три основных набора взаимосвязей, что и на этапе 1. Единственными изменениями в этих ограничениях являются различные проектные предположения для трех стадий и включение применимых переменных стадии. Хотя ограничения равенства и неравенства для этапов 2 и 3 не приводятся до конца этого раздела, ниже рассматриваются изменения по сравнению с этапом 1.

------------------------------------------------------------------------

Уравнения для определения веса для этапов 2 и 3 отличаются дробным значением веса планера по отношению к общему весу инертных на этапе. Произвольные значения для этапов 2 и 3 составляют 0,6 и 0,7, соответственно. Границы ограничений неравенства для этапов 2 и 3 изменены по сравнению с границами этапа 1, чтобы быть типичными для хороших проектных значений для средней и верхней ступеней, соответственно. Границы для этапов 2 и 3 выбираются произвольно так же, как и для этапа 1. Переменные в выражениях для массовой доли ступени и ограничений на отношение тяги к массе находятся в соответствии с последовательностью отделения ступеней и/или их сжигания. Таким образом, для ступеней 2 и 3 условия для этих двух ограничений не включают переменные для ступени или ступеней, которые уже сгорели и отделились. Переменные в условиях других ограничений содержат только переменные описываемой стадии. На этом обсуждение ограничений стадий 2 и 3 завершено. Фактические ограничения, используемые в модели, приведены в конце этого раздела.

**Ограничение приборного блока** В целевой функции присутствует только один параметр ракеты-носителя - приборный блок. Этот параметр, вес приборного блока в тысячах фунтов, должен быть ограничен. Поскольку прямой связи между весом приборного блока и другими переменными и параметрами, рассматриваемыми в данной модели, не существует, ограничение выполняется с помощью произвольного ограничения. Поскольку размер и вес приборного блока зависят от сложности, требуемой от системы наведения и управления, допущения, принятые в модели примера, делают эту переменную несколько бессмысленной. Поэтому ограничение на приборный блок основано не на требованиях примера миссии, а на типе требований, которые могут быть предъявлены к ракете-носителю, подобной приведенному в примере. Таким образом, переменная ограничена следующим образом $$2.5 \leq X_{41} \leq 4.0$$ Поскольку переменная выражена в тысячах фунтов, границы также выражены в тысячах фунтов

**Общие ограничения ракеты-носителя** Общие ограничения ракеты-носителя представляют собой совокупность ограничений отдельных ступеней. Три основных типа ограничений гарантируют, что каждая переменная модели ограничена и находится в желаемых пределах. Ограничения, связанные с определением взаимосвязей, гарантируют, что переменные, не используемые в параметрах производительности или отношениях, ограничиваются через их связь с теми переменными, которые используются. Базовые отношения производительности обеспечивают поддержание надлежащих отношений между конструкциями отдельных этапов.

------------------------------------------------------------------------

Желаемые эксплуатационные параметры гарантируют, что ракета-носитель в целом способна выполнить поставленную задачу. Общая скорость ракеты-носителя является суммой приращений скоростей отдельных ступеней. Таким образом, общая скорость ракеты-носителя определяется следующим образом $$v_t=v_1+v_2+v_3$$ Это уравнение в переменных модели имеет вид: $$v_t=[(\dfrac{X_{14}t_1\overline{g}}{X_{15}})\ln(\dfrac{1}{X_{13}})] + [(\dfrac{X_{24}t_2\overline{g}}{X_{25}})\ln(\dfrac{1}{X_{23}})] + [(\dfrac{X_{34}t_3\overline{g}}{X_{35}})\ln(\dfrac{1}{X_{33}})].$$ Это уравнение дает конечную скорость, которой может достичь аппарат в безгравитационном вакууме, если вся пропульсивная энергия всех ступеней в одном направлении. Если требование к скорости полета учитывает расчеты идеальных скоростей, то ограничение на скорость ухода от Земли определяется следующими неравенствами: $$35,000 \leq v_t \leq 50,000.$$ Это завершает ограничение скорости в модели

**Краткое описание ограничений** Все ограничения были рассмотрены. Ограничения, необходимые для модели, обобщены следующим образом:

**Этап 1**

$$(0.5)X_{12}=X_{11},
X_{14}=(5)X_{16},
X_{13}=(\dfrac{{X_{12}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}}
{{X_{12}+X_{15}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL}}),
12X_{12} \leq X_{15} \leq 16X_{12},
125 \leq X_{17} \leq 150,
240 \leq \dfrac{X_{14}t_1}{X_15} \leq 290,
0.25 \leq X_{13} \leq 0.30,
1.2 \leq \dfrac{X_{14}}{X_{12}+X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL} \leq 1.4,
$$

------------------------------------------------------------------------

**Этап 2** \$\$ (0.6)X\_{22}=X\_{21}, X\_{24}=(5)X\_{26}, X\_{23}=(\dfrac{{X_{22}+X_{32}+X_{35}+X_{41}+PL}} {{X\_{22}+X\_{25}+X\_{32}+X\_{35}+X\_{41}+PL}}), 10X\_{22} \leq X\_{25} \leq 12X\_{22}, 75 \leq X\_{27} \leq 100, 240 \leq \dfrac{X_{24}t_2}{X_{25}} \leq 290, 0.24 \leq X\_{23} \leq 0.29, 0.6 \leq \dfrac{X_{24}}{X_{22}+X_{25}+X_{32}+X_{35}+X_{41}+PL} \leq 0.75,

\$\$

**Этап 3** $$
(0.7)X_{32}=X_{31},
X_{34}=X_{36},
X_{33}=(\dfrac{{X_{32}+X_{41}+PL}}
{{X_{32}+X_{35}+X_{41}+PL}}),
7X_{32} \leq X_{35} \leq 9X_{32},
50 \leq X_{37} \leq 70,
340 \leq \dfrac{X_{34}t_3}{X_{35}} \leq 375,
0.16 \leq X_{33} \leq 0.21,
0.7 \leq \dfrac{X_{34}}{X_{32}+X_{35}+X_{41}+PL} \leq 0.9,
$$

**Инструментальная единица** $$2.5 \leq X_{41} + 4.0,$$ **Всего по ракете-носителю** $$35,000 \leq [(\dfrac{X_{14}t_1\overline{g}}{X_{15}})\ln(\dfrac{1}{X_{13}})] + [(\dfrac{X_{24}t_2\overline{g}}{X_{25}})\ln(\dfrac{1}{X_{23}})] + [(\dfrac{X_{34}t_3\overline{g}}{X_{35}})\ln(\dfrac{1}{X_{33}})] \leq 50,000$$ ---

### 7.4 ПРИМЕНЕНИЕ МОДЕЛИ

**Метод решения и результаты**

Задача нелинейного программирования была решена с помощью метода последовательной минимизации без ограничений. Значения, приведенные в таблице 7.1 для модели I, соответствуют целевой функции и ограничениям, разработанным в разделах 7.2 и 7.3. Параметр объективной функции $K_1$ был задан равным 10, а масса PL была принята равной 20,000 фунтов. Таким образом, программа состояла из разработки, строительства и запуска 10 ракет-носителей. Значения целевой функции, рассчитанные для наборов начальных точек a и b, составили S3,36 млрд и S3,16 млрд соответственно. Значение целевой функции, вычисленное при оптимальном решении модели I, составило S2,53 миллиарда. Один и тот же ответ (оптимальное решение) был получен для обоих наборов стартовых точек

**Таблица 7.1 Начальные и решенные значения переменных для моделей I и II**

| Переменная | Набор начальных точек a | Набор начальных точек b | Решение для модели 1 | Решение для модели 2 |
|---------------|---------------|---------------|---------------|---------------|
| $X_{11}$ | 150 | 100 | 68 | 54 |
| $X_{12}$ | 300 | 200 | 136 | 109 |
| $X_{13}$ | 0.28 | 0.29 | 0.3 | 0.3 |
| $X_{14}$ | 7000 | 5500 | 3733 | 3353 |
| $X_{15}$ | 4000 | 3000 | 2177 | 1956 |
| $X_{16}$ | 1400 | 1100 | 746 | 671 |
| $X_{17}$ | 135 | 150 | 125 | 125 |
| $X_{21}$ | 54 | 39 | 28 | 24 |
| $X_{22}$ | 90 | 65 | 47 | 40 |
| $X_{23}$ | 0.27 | 0.286 | 0.29 | 0.29 |
| $X_{24}$ | 800 | 700 | 478 | 438 |
| $X_{25}$ | 900 | 750 | 566 | 518 |
| $X_{26}$ | 160 | 140 | 96 | 88 |
| $X_{27}$ | 85 | 100 | 75 | 75 |
| $X_{31}$ | 17.5 | 16 | 11 | 9.5 |
| $X_{32}$ | 25 | 23 | 16 | 13.6 |
| $X_{33}$ | 0.19 | 0.20 | 0.21 | 0.21 |
| $X_{34}$ | 200 | 180 | 129 | 120 |
| $X_{35}$ | 200 | 190 | 145 | 136 |
| $X_{36}$ | 200 | 180 | 129 | 120 |
| $X_{37}$ | 60 | 70 | 50 | 50 |
| $X_{41}$ | 3 | 4 | 2.5 | 2.5 |
| $t_{1}$ | 150 | 145 | 155 | 155 |
| $t_{2}$ | 300 | 275 | 314 | 314 |
| $t_{3}$ | 350 | 37 | 403 | 403 |
| Общая стоимость(миллиарды) | \$3.16 | \$3.16 | \$2.53 | \$2.53 |

------------------------------------------------------------------------

Вариант модели I (названный моделью II) был решен с использованием различных ограничений на структурную целостность. Границы кратного отношения массы ракеты к массе ступени были изменены для 1-й ступени с 12 и 16 до 10 и 18. Для этапа 2 границы были изменены с 8 и 12 на 7 и 13, а для этапа 3 - с 7 и 9 на 6 и 10. Использовались те же наборы начальных точек, что и в модели I, и значения решений также приведены в табл. 7.1. Значение целевой функции, вычисленное при решении модели II, составило S2,33 млрд. Для обоих наборов начальных точек было получено одно и то же оптимальное решение.

**Анализ результатов**

Одной из самых сложных проблем в нелинейном программировании является работа с локальными и глобальными минимумами. Не существует алгоритма, гарантирующего сходимость к глобальному минимуму для сложной, нелинейной, невыпуклой задачи программирования, такой как модель, разработанная в этой главе. Однако при использовании различных начальных значений сходимость к одному и тому же оптимальному решению указывает на то, что глобальный минимум, возможно, был достигнут. Изучение результатов компьютерных прогонов для моделей I и II показало, что значения решений для переменных практически одинаковы для обоих наборов начальных точек. Получение одинаковых результатов для двух наборов начальных точек в течение нескольких прогонов указывает на то, что значения целевой функции, полученные для двух моделей, могут быть глобальными минимумами.

Интересно отметить значение решения для массовой доли стадии. Значения решения для всех трех ступеней в обоих вариантах модели достигают своих верхних границ. Это указывает на то, что, хотя более низкая массовая доля желательна с точки зрения инженерного проектирования, стоимость ее достижения выше, чем полученный выигрыш в производительности. Это, по крайней мере, верно в рамках ограничений модели, и интуитивно можно сказать, что это верно и в области проектирования ракет. Это можно показать на практике, поскольку очевидно, что после определенного момента совершенствование конструкции уже нецелесообразно, и требуется просто более крупный аппарат в целом.

Когда границы ограничения структурной целостности для второй вариации модели были изменены, переменные снова достигли верхней границы для всех трех ступеней. Когда ограничение структурной целостности удаляется, вес конструкции ступени стремится к нулю, а вес ракетного топлива становится настолько большим, насколько позволяют оставшиеся ограничения. Таким образом, отношение массы ракеты к массе ступени будет настолько большим, насколько позволит ограничение структурной целостности. Это указывает на то, что фактор структурной сложности, учитывающий большую сложность конструкции ступени с высоким отношением веса топлива к весу ступени, может быть выгодно включен в целевую функцию.

Отношение тяги к массе достигло нижней границы для всех трех ступеней и обоих вариантов модели. Анализ этого результата такой же, как и для массовой доли ступени. Чем больше отношение тяги к массе, тем выше стоимость, а в рамках модели увеличение эксплуатационных возможностей не требовалось.

Ограничение удельного импульса для ступеней 1 и 2 осталось неизменным между двумя вариантами модели и между двумя ступенями. Ожидается, что это ограничение будет одинаково реагировать для двух ступеней, поскольку они используют одно и то же топливо; однако не ожидается, что оно останется неизменным. Возможно, что модель чрезмерно ограничена в этой области или что это может быть отражением оптимальной точки в CER, которая одинакова для двух стадий. Какая из этих возможностей на самом деле имеет место, выяснить не удалось.

Ограничение скорости не было доведено до нижней границы ни в одной из вариаций модели. В обеих моделях ограничение скорости достигло значения 38,632 футов/сек. Это указывает на то, что для получения транспортного средства оптимального размера для достижения целей минимальной скорости необходимо ослабить ограничения. Этого можно достичь путем снятия ограничений на отношение тяги к массе, которые, наряду с временем сгорания, определяют ускорение. При ослаблении некоторых ограничений для достижения цели минимальной скорости необходимо учитывать необходимость сохранения рациональной конструкции ракеты-носителя и не допускать, чтобы основные параметры конструкции достигли невыполнимых значений параметры конструкции достигли невыполнимых значений

Поскольку переменные длины ступени не связаны с ограничениями производительности, используемыми в модели, эти переменные могут быть скорректированы после компьютерного прогона. Таким образом, длина ступени может быть приведена в надлежащее соотношение с другими переменными конструкции ступени. Функция общей стоимости будет затронута, и включение новой длины приведет к более точному значению общей стоимости.

Решение задачи нелинейного программирования показало, что этот тип сложной нелинейной модели является вычислительно реализуемым. Анализ результатов дал некоторое представление о полезности модели, и дальнейшее обсуждение этого вопроса приведено в следующем подразделе. Следует подчеркнуть, что разработанная модель является прототипом и что в нее могут быть внесены многочисленные улучшения. Обсуждение некоторых из предложенных улучшений приведено в одном из последующих подразделов.

**Чувствительность модели к изменениям в ограничениях**

С решением любой задачи нелинейного программирования связан набор значений, называемых «теневыми ценами» или обобщенными множителями Лагранжа, по одному на каждое ограничение неравенства, которые отражают чувствительность значения целевой функции к ужесточению или ослаблению ограничений. Для тех ограничений, которые не являются обязательными в решении, соответствующие теневые цены равны нулю. Интересны теневые цены, связанные с обязательными ограничениями. Теория, лежащая в основе использования теневых цен, заключается в том, что если изменить исходную задачу и ослабить i-е ограничение на величину $\delta$

**Таблица 7.2 Чувствительность к изменению пределов обязательных ограничений в модели I**

| Ограничение | Изменение единицы измерения | Экономия общих затрат (млн. долл.) |
|----------------------------|--------------------|-------------------------|
| Массовая доля ступени, верхняя граница |  |  |
| Ступень 1 | +0.01 | 41.3 |
| Ступень 2 | +0.01 | 50.0 |
| Ступень 3 | +0.01 | 121.5 |
| Отношение тяги к весу, нижний предел |  |  |
| Ступень 1 | -0.01 | 24.7 |
| Ступень 2 | -0.01 | 13.1 |
| Ступень 3 | -0.01 | 15.8 |

$[g_i(x) + \delta \geq 0]$, то изменение оптимального значения объективной функции будет примерно равно $-\sigma \overline{\mu_i}$, где $\overline{\mu_i}$ - теневая цена, связанная с i-м ограничением при решении исходной задачи.

Использование этих значений особенно важно в тех задачах проектирования, где интересует чувствительность модели к изменениям в требованиях к конструкции. Это можно проиллюстрировать на примере теневых цен, полученных с помощью метода последовательной минимизации без ограничений.

Два ограничения, которые необходимо рассмотреть, - это неравенства по массовой доле ступени и по соотношению тяги к массе. Ограничение на массовую долю ступени ищет верхнюю границу для всех трех ступеней в обеих моделях. Ограничение по соотношению тяги к массе стремится к нижней границе для всех трех ступеней в обеих моделях. В табл. 7.2 показана экономия в миллионах долларов, которую можно получить, если позволить массовой доле ступени быть на сотую долю выше верхних границ в исходной модели, и экономия, если позволить ограничению тяги к массе быть на десятую долю ниже нижних границ в исходной модели. Таким образом, в табл. 7.2 показана чувствительность целевой функции к единичным изменениям пределов обязательных ограничений.

**Возможные расширения модели**

Для улучшения результатов, получаемых с помощью модели, можно использовать два типа изменений. Один тип изменений - это вариации в рамках существующей модели. Второй тип изменений - это построение новой модели, использующей основные идеи модели-прототипа. Один из типов изменений, который уже был реализован и обсуждался, - это изменение значений границ ограничений. Подобные возмущения модели полезны для анализа результатов и решения некоторых изменений в конструкции. Еще одна легко выполнимая вариация - изменение основных проектных предположений, таких как количество ступеней или количество двигателей на ступень. Это может быть полезно для определения оптимальной схемы размещения ступеней. Возможны и другие многочисленные изменения в рамках модели прототипа.

------------------------------------------------------------------------

Второй тип изменений, по сути, требует построения новой модели. Это желательно с нескольких точек зрения. Новые модели могут быть разработаны с учетом специфики использования, определяющей их дизайн. Кроме того, новые модели могут включать в себя новейшие CER и использовать более сложные ограничения производительности, если это необходимо. С появлением более точных CER можно будет рассматривать больше подсистем и, возможно, на более низком уровне детализации, чем подсистема. По мере разработки моделей программирования, несомненно, станут очевидными и многие другие области совершенствования.

**Концептуальное и предварительное проектирование и расчет стоимости**

Модель, представленная в данной статье, применима к этапам концептуального и предварительного проектирования при разработке ракеты-носителя. Ее полезность ограничена теми этапами, которые выполняются до детального определения программы. Однако на первых двух этапах модель может служить гибким, быстро реагирующим инструментом планирования. В настоящее время описательные модели стоимости используются для планирования будущих проектов в NASA и в промышленности. Эти модели используются для прогнозирования затрат, финансирования и составления графиков. Другие модели программирования в ограниченной степени используются в инженерном проектировании на этапах концептуального и предварительного проектирования. Однако модель, позволяющая учитывать как инженерное проектирование, так и расчет затрат путем оптимизации, не используется. Данная модель является прототипом, призванным заполнить этот пробел.

Трудности с получением эффективной модели затрат одинаковы независимо от того, является ли она описательной или оптимизационной. Обе модели ограничены степенью точности ССВ и редко могут опускаться ниже уровня подсистем. Дополнительная трудность оптимизационной модели заключается в том, что ее очень сложно решить с помощью методов математического программирования. Использование SUMT и будущих усовершенствований этого или других алгоритмов обещает открыть двери для сложных моделей программирования всей системы.
