# Теория игр {#sec-practice-game-theory}

::::: {.content-hidden when-profile="practice"}
## Темы {#sec-practice-game-theory-topics}

В практической работе будут предложены задачи на следующие темы:

-   @sec-game-theory-overview-representation
-   @sec-game-theory-overview-solution
-   @sec-game-theory-overview-domination
-   @sec-game-theory-overview-nature

::: {#exm-practice-game-theory}
### Примерчик

Задание
:::

::: {#sol-practice-game-theory}
Решение
:::
:::::

::::: {.content-hidden when-profile="student"}
:::: {#exr-practice-game-theory-representation}
## Орёл или решка

1-й игрок подбрасывает монету, на которой выпадает "орёл" или "решка". Затем 2-й игрок, независимо от первого, подбрасывает монету, и на монете 2-го игрока также выпадает одна из сторон. 2-й игрок платит 1 руб. 1-му игроку, если выпавшие стороны монет одинаковые, или -1 руб., если они различны. Таким образом, 1-й игрок играет на максимум, 2-й игрок -- на минимум.

Записать игру в развёрнутой и нормальной форме.

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="practice"}

::: {.callout-note appearance="minimal" title="Оценка"}
2
:::
::::
:::::

::::: {.content-hidden when-profile="student"}
:::: {#exr-practice-game-theory-solution}
## Решение в чистых стратегиях

Определите верхнюю, нижнюю чистые цены игры, найдите решение игры в чистых стратегиях для матричной игры, заданной платёжной матрицей

$$
\Pi = 
\begin{pmatrix}
9 & 5 & 6 & 7 \\
1 & 4 & 3 & 8 \\
6 & 3 & 2 & -4
\end{pmatrix}
$$

::: {.callout-note appearance="minimal" title="Оценка"}
2
:::
::::
:::::

::::: {.content-hidden when-profile="student"}
:::: {#exr-practice-game-theory-simplification}
## Доминирование

Воспользовавшись принципом доминирования исключите строки, найдите решение в чистых стратегиях

$$
\Pi = 
\begin{pmatrix}
4 & 5 & 6 & 7 \\
3 & 4 & 6 & 5 \\
7 & 6 & 10 & 8 \\
8 & 5 & 4 & 3
\end{pmatrix}
$$

[`\vspace{4cm}`{=latex}]{.content-visible when-profile="practice"}

::: {.callout-note appearance="minimal" title="Оценка"}
3
:::
::::
:::::

::::: {.content-hidden when-profile="student"}
:::: {#exr-practice-game-theory-nature}
## Игра с природой

<!--Шиловский-->

Телефонная компания должна определить уровень своих возможностей по предоставлению телефонных услуг так, чтобы удовлетворит спрос своих клиентов на планируемый период.

Для каждого уровня спроса существует наилучший уровень возможностей телефонной компании (например, с точки зрения возможных затрат на ввод нового тарифа). Отклонения от этих уровней могут приводить к дополнительным затратам. В матрице таблице приводятся сведения, определяющие прогнозируемые затраты на развитие телефонных возможностей. Имеются четыре варианта спроса на телефонные услуги, что равнозначно наличию четырёх состояний природы $S_1, S_2, S_3, S_4$. Известно также четыре варианта предоставляемых компанией телефонных услуг $R_1,R_2,R_3,R_4$.

Воспользовавшись критериями Лапласа и Вальда выбрать оптимальную стратегию.

|                          |          |        |               |        |
|:------------------------:|:--------:|:------:|:-------------:|:------:|
| Варианты предоставляемых | Варианты | спроса | на телефонные | услуги |
|     телефонных услуг     |  $S_1$   | $S_2$  |     $S_3$     | $S_4$  |
|          $R_1$           |    7     |   10   |      18       |   22   |
|          $R_2$           |    9     |   6    |       8       |   25   |
|          $R_3$           |    21    |   18   |      16       |   21   |
|          $R_4$           |    24    |   22   |      20       |   26   |

::: {.callout-note appearance="minimal" title="Оценка"}
3
:::
::::
:::::
