project:
  type: book
  post-render:
    - scripts/widgets/resolve-lib-ref.R
    - scripts/mathjax/resolve-lib-ref.R


profile:
  group:
    - [base, advanced, exam-gen]
    - [dev, prod]

book:
  title: "Исследование операций"
  author: "Афоненко Анатолий"
  date: today
  date-format: long

  repo-url: "https://github.com/AfonenkoA/Operations-Research"
  repo-actions: [issue]
  repo-branch: master

lang: ru


bibliography:
  - references.bib
  - exam/1/ref.bib

csl: gost-r-7-0-5-2008-numeric.csl

format:
  html:
    number-depth: 3
    theme: cosmo
    html-math-method:
      method: mathjax
      url: QUARTO_MATHJAX_SVG

editor: visual
