project:
  type: book
  output-dir: _full-book

book:
  chapters:
    - index.qmd
    - TODO.md
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r/overview.qmd
      chapters:
        - r/lang/basic.qmd
        - r/lang/advanced.qmd

    - part: python/lang/overview.qmd
      chapters:
        - python/lang/advanced.qmd
        - python/lang/basic.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical/solution.qmd
        - linear/graphical/sensetivity.qmd
        - linear/dual-problem.qmd
        - linear/simplex/alghoritm.qmd
        - linear/simplex/sensetivity.qmd
        - linear/simplex/special-cases.qmd
        - linear/simplex/artificial-initial-solution.qmd
        - linear/integer.qmd
        - linear/transport.qmd

    - part: combinatorial/overview.qmd
      chapters:
        - combinatorial/graph-theory.qmd
        - combinatorial/problems/constraint-satisfy.qmd
        - combinatorial/problems/optimal-facility-location.qmd
        - combinatorial/problems/network.qmd
        - combinatorial/problems/shortest-path.qmd
        - combinatorial/problems/knapsack.qmd
        - combinatorial/problems/bin-packing.qmd
        - combinatorial/problems/minimum-spanning-tree.qmd
        - combinatorial/problems/travelling-salesman.qmd
        - combinatorial/algorithm/dijkstra.qmd
        - combinatorial/algorithm/branch-and-bound.qmd
        - combinatorial/algorithm/dynamic-programming.qmd
        - combinatorial/algorithm/backtracking.qmd

    - part: minizinc/overview.qmd
      chapters:
        - minizinc/basic.qmd
        - minizinc/advanced.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical/one/main.qmd
        - nonlinear/unconstrained/analytical/many/main.qmd
        - nonlinear/unconstrained/numerical/one/main.qmd
        - nonlinear/unconstrained/numerical/many/direct/main.qmd
        - nonlinear/unconstrained/numerical/many/gradient/main.qmd
        - nonlinear/constrained/analytical/one/main.qmd
        - nonlinear/constrained/analytical/many/main.qmd
        - nonlinear/constrained/numerical/conversion-to-unconstrained.qmd
        - nonlinear/constrained/numerical/one/main.qmd
        - nonlinear/constrained/numerical/many/direct/main.qmd
        - nonlinear/constrained/numerical/many/gradient/main.qmd

    - part: evolutionary/overview.qmd
      chapters:
        - evolutionary/simulated-annealing.qmd
        - evolutionary/ant-colony.qmd
        - evolutionary/genetic.qmd

    - part: game-theory/overview.qmd
      chapters:
        - game-theory/matrix.qmd

    - part: multi-objective/overview.qmd

    - part: "Задания. Программирование"
      chapters:
        - lab/programming/r/main.qmd

    - part: "Задания. Алгоритмы"
      chapters:
        - lab/alghorithm/linear/algebra/main.qmd
        - lab/alghorithm/graph-theory/main.qmd
        - lab/alghorithm/dynamic-programming/main.qmd
        - lab/alghorithm/nonlinear/main.qmd
        - lab/alghorithm/evolutionary/main.qmd


    - part: "Задания. Моделирование"
      chapters:
        - lab/model/basic/main.qmd

        - lab/model/linear/standard/main.qmd
        - lab/model/linear/transport/main.qmd
        - lab/model/linear/integer/main.qmd
        - lab/model/network/main.qmd
        - lab/model/nonlinear/main.qmd
        - lab/model/evolutionary/main.qmd
        - lab/model/game-theory/main.qmd
        - lab/model/multi-objective/main.qmd

    - part: "Задания. Дополнительно"
      chapters:
        - lab/extra/programming/r/main.qmd
        - lab/extra/linear/main.qmd
        - lab/extra/network/main.qmd
        - lab/extra/constraint/main.qmd
        - lab/extra/packing/main.qmd
        - lab/extra/nonlinear/main.qmd
        - lab/extra/evolutionary/main.qmd

    - part: "Практические работы"
      chapters:
        - practice/basic-model/main.qmd
        - practice/linear/algebra/main.qmd
        - practice/linear/graphical/main.qmd
        - practice/linear/model/main.qmd
        - practice/linear/simplex/main.qmd
        - practice/network/main.qmd
        - practice/evolutionary/main.qmd
        - practice/nonlinear/main.qmd
        - practice/game-theory/main.qmd

    - part: "Проверочные работы"
      chapters:
        - exam/basic-model/main.qmd
        - exam/linear/main.qmd
        - exam/network/main.qmd
        - exam/nonlinear/main.qmd
        - exam/evolutionary/main.qmd

    - references.qmd

  appendices:
    - lab/report.qmd
    - part: "Язык программирования R"
      chapters:
        - r/tools/renv.qmd
        - r/tools/base.qmd
        - r/tools/stats.qmd
        - r/tools/igraph.qmd
        - r/tools/pracma.qmd
        - r/tools/smoof.qmd

        - r/tools/tidyverse/purrr.qmd
        - r/tools/tidyverse/tibble.qmd
        - r/tools/tidyverse/dplyr.qmd
        - r/tools/tidyverse/tidyr.qmd

        - r/tools/plot/plotly.qmd
        - r/tools/plot/ggplot2.qmd

        - r/tools/solver/linear/transport.qmd
        - r/tools/solver/linear/lpsolve.qmd
        - r/tools/solver/linear/clue.qmd

        - r/tools/solver/nonlinear/nloptr/analysis.qmd
        - r/tools/solver/nonlinear/nloptr/local/unconstrained.qmd
        - r/tools/solver/nonlinear/nloptr/local/constrained/inequality.qmd
        - r/tools/solver/nonlinear/nloptr/local/constrained/equality.qmd

        - r/tools/solver/evolutionary/gensa.qmd
        - r/tools/solver/evolutionary/pso.qmd
        - r/tools/solver/evolutionary/ga.qmd
        - r/tools/solver/evolutionary/tsp.qmd

    - part: "Язык программирования Python"
      chapters:
        - python/tools/minizinc.qmd
