project:
  type: book
  output-dir: _test

book:
  chapters:
        - index.qmd
        - r/tools/solver/evolutionary/gensa.qmd
        - r/tools/solver/evolutionary/pso.qmd
        - r/tools/solver/evolutionary/ga.qmd
        - r/tools/solver/evolutionary/tsp.qmd
        - python/tools/minizinc.qmd
