project:
  type: book
  output-dir: _sbook

book:
  chapters:
    - index.qmd
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r/overview.qmd
      chapters:
        - r/lang/basic.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical/solution.qmd
        - linear/graphical/sensetivity.qmd
        - linear/simplex/special-cases.qmd
        - linear/integer.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical/one/main.qmd
        - nonlinear/unconstrained/analytical/many/main.qmd
        - nonlinear/constrained/analytical/main.qmd
        - nonlinear/constrained/numerical/conversion-to-unconstrained.qmd

    - part: "Задания. Алгоритмы"
      chapters:
        - lab/alghorithm/programming/r/main.qmd
        - lab/alghorithm/linear/algebra/main.qmd
        - lab/alghorithm/nonlinear/main.qmd

    - part: "Задания. Моделирование"
      chapters:
        - lab/model/basic/main.qmd
        - lab/model/linear/standard/main.qmd
        - lab/model/linear/transport/main.qmd
        - lab/model/linear/integer/main.qmd
        - lab/model/network/main.qmd
        - lab/model/nonlinear/main.qmd

    - part: "Задания. Дополнительно"
      chapters:
        - lab/extra/programming/r/main.qmd
        - lab/extra/network/main.qmd
        - lab/extra/evolutionary/main.qmd

    - part: "Практические работы"
      chapters:
        - practice/basic-model/main.qmd
        - practice/linear/algebra/main.qmd
        - practice/linear/graphical/main.qmd
        - practice/linear/model/main.qmd
        - practice/linear/simplex/main.qmd

    - references.qmd

  appendices:
    - part: "Язык программирования R"
      chapters:
        - r/tools/renv.qmd
        - r/tools/pracma.qmd
        - r/tools/smoof.qmd
        - r/tools/stats.qmd

        - r/tools/plot/plotly.qmd

        - r/tools/solver/linear/transport.qmd
        - r/tools/solver/linear/lpsolve.qmd
        - r/tools/solver/linear/clue.qmd

        - r/tools/solver/nonlinear/nloptr/analysis.qmd
        - r/tools/solver/nonlinear/nloptr/local/unconstrained.qmd
        - r/tools/solver/nonlinear/nloptr/local/constrained/inequality.qmd
        - r/tools/solver/nonlinear/nloptr/local/constrained/equality.qmd

        - r/tools/solver/evolutionary/gensa.qmd
        - r/tools/solver/evolutionary/pso.qmd
        - r/tools/solver/evolutionary/ga.qmd
        - r/tools/solver/evolutionary/tsp.qmd
