project:
  type: book

profile:
  group:
    - [full, student, exam, test]
    - [dev, prod]
    - [html, pdf, pdf-exam]

book:
  title: "Исследование операций"
  author: "Афоненко Анатолий"
  date: today
  date-format: long

  repo-url: "https://github.com/AfonenkoA/Operations-Research"
  repo-actions: [issue]
  repo-branch: master

lang: ru

bibliography:
  - references.bib
  - lab/2/ref.bib
  - exam/1/ref.bib

csl: gost-r-7-0-5-2008-numeric.csl

editor: visual
engine: knitr
