project:
  type: book
  output-dir: _full-book

book:
  chapters:
    - index.qmd
    - TODO.md
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r/overview.qmd
      chapters:
        - r/lang/basic.qmd
        - r/lang/advanced.qmd

    - part: minizinc/overview.qmd
      chapters:
        - minizinc/basic.qmd
        - minizinc/advanced.qmd

    - part: python/lang/overview.qmd
      chapters:
        - python/lang/advanced.qmd
        - python/lang/basic.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical/solution.qmd
        - linear/graphical/sensetivity.qmd
        - linear/dual-problem.qmd
        - linear/simplex/alghoritm.qmd
        - linear/simplex/sensetivity.qmd
        - linear/simplex/special-cases.qmd
        - linear/simplex/artificial-initial-solution.qmd
        - linear/integer.qmd
        - linear/transport.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical-one.qmd
        - nonlinear/unconstrained/analytical-many.qmd
        - nonlinear/constrained/analytical-one.qmd
        - nonlinear/constrained/analytical-many.qmd

    - part: combinatorial/overview.qmd
      chapters:
        - combinatorial/graph-theory.qmd
        - combinatorial/problems/constraint-satisfy.qmd
        - combinatorial/problems/optimal-facility-location.qmd
        - combinatorial/problems/network.qmd
        - combinatorial/problems/shortest-path.qmd
        - combinatorial/problems/knapsack.qmd
        - combinatorial/problems/bin-packing.qmd
        - combinatorial/problems/minimum-spanning-tree.qmd
        - combinatorial/problems/travelling-salesman.qmd
        - combinatorial/algorithm/dijkstra.qmd
        - combinatorial/algorithm/branch-and-bound.qmd
        - combinatorial/algorithm/dynamic-programming.qmd
        - combinatorial/algorithm/backtracking.qmd

    - part: evolutionary/overview.qmd
      chapters:
        - evolutionary/simulated-annealing.qmd
        - evolutionary/ant-colony.qmd
        - evolutionary/genetic.qmd

    - part: game-theory/overview.qmd
      chapters:
        - game-theory/matrix.qmd

    - part: multi-objective/overview.qmd

    - part: "Лабораторные работы"
      chapters:
        - lab/report.qmd
        - lab/programming/r/main.qmd
        - lab/basic-model/main.qmd

        - lab/linear/algebra/main.qmd
        - lab/linear/programming/main.qmd
        - lab/linear/integer/main.qmd
        - lab/linear/transport/main.qmd

        - lab/combinatorial/graph-theory/main.qmd
        - lab/combinatorial/network/main.qmd
        - lab/combinatorial/constraint/main.qmd
        - lab/combinatorial/packing/main.qmd
        - lab/combinatorial/dynamic-programming/main.qmd

        - lab/nonlinear/main.qmd
        - lab/evolutionary/main.qmd
        - lab/game-theory/main.qmd
        - lab/multi-objective/main.qmd

    - part: "Практические работы"
      chapters:
        - practice/basic-model/main.qmd
        - practice/linear/algebra/main.qmd
        - practice/linear/graphical/main.qmd
        - practice/linear/model/main.qmd
        - practice/linear/simplex/main.qmd
        - practice/network/main.qmd
        - practice/evolutionary/main.qmd
        - practice/nonlinear/main.qmd
        - practice/game-theory/main.qmd

    - part: "Проверочные работы"
      chapters:
        - exam/basic-model/main.qmd
        - exam/linear/main.qmd
        - exam/network/main.qmd
        - exam/nonlinear/main.qmd
        - exam/evolutionary/main.qmd

    - references.qmd

  appendices:
    - part: "Язык программирования R"
      chapters:
        - r/tools/basic.qmd
        - r/tools/renv.qmd
        - r/tools/plotly.qmd
        - r/tools/ggplot2.qmd
        - r/tools/tidyverse/tibble.qmd
        - r/tools/tidyverse/purrr.qmd
        - r/tools/tidyverse/dplyr.qmd
        - r/tools/tidyverse/tidyr.qmd
        - r/tools/solver/lpsolve.qmd
        - r/tools/solver/transport.qmd
        - r/tools/solver/clue.qmd
        - r/tools/igraph.qmd
    - part: "Язык программирования Python"
      chapters:
        - python/tools/minizinc.qmd
