book:
  chapters:
    - index.qmd
    - TODO.md
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r-lang/overview.qmd
      chapters:
        - r-lang/basic.qmd
        - r-lang/advanced.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical-solution.qmd
        - linear/sensetivity.qmd
        - linear/simplex-spec.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical-one.qmd
        - nonlinear/unconstrained/analytical-many.qmd
        - nonlinear/constrained/analytical-many.qmd

    - part: "Лабораторные работы"
      chapters:
        - lab/1/intro.qmd
        - lab/2/linear.qmd
    - references.qmd


  appendices:
    - part: "Язык программирования R"
      chapters:
        - r-tools/renv.qmd
        - r-tools/plotly.qmd
        - r-tools/purrr.qmd
        - r-tools/lpsolve.qmd

