project:
  type: book

book:
  title: "Operations Research"
  author: "Афоненко Анатолий"
  date: today
  date-format: long

  chapters:
    - index.qmd

    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r-lang/overview.qmd
      chapters:
        - r-lang/basic.qmd
        - r-lang/advanced.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical-solution.qmd
        - linear/sensetivity.qmd
        - linear/dual.qmd
        - linear/simplex.qmd
        - linear/simplex-ext.qmd
        - linear/integer.qmd
        - linear/transport.qmd
        - linear/network.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical-one.qmd
        - nonlinear/unconstrained/analytical-many.qmd

    - part: graph-theory/overview.qmd
      chapters:
        - graph-theory/dijkstra.qmd

    - part: game-theory/overview.qmd
      chapters:
        - game-theory/matrix.qmd

    - part: "Лабораторные работы"
      chapters:
        - lab1/intro.qmd
        - lab2/linear.qmd


  appendices:
    - references.qmd
    - part: "R"
      chapters:
        - r-tools/figure-plot.qmd
        - r-tools/linear.qmd
        - r-tools/renv.qmd


bibliography: references.bib

freeze: auto
cache: true

format:
  html:
    number-depth: 3
    theme: cosmo
    html-math-method: katex

editor: visual
