project:
  type: book
  output-dir: _student-book

book:
  chapters:
    - index.qmd
    - TODO.md
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r/overview.qmd
      chapters:
        - r/lang/basic.qmd
        - r/lang/advanced.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical/solution.qmd
        - linear/simplex/sensetivity.qmd
        - linear/simplex/special-cases.qmd
        - linear/integer.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical-one.qmd
        - nonlinear/unconstrained/analytical-many.qmd
        - nonlinear/constrained/analytical-many.qmd

    - part: "Лабораторные работы"
      chapters:
        - lab/programming/r/main.qmd
        - lab/basic-model/main.qmd
        - lab/linear/algebra/main.qmd
        - lab/linear/programming/main.qmd
    - references.qmd


  appendices:
    - part: "Язык программирования R"
      chapters:
        - r/tools/renv.qmd
        - r/tools/plotly.qmd
        - r/tools/tidyverse/purrr.qmd
        - r/tools/lpsolve.qmd
