book:
  chapters:
    - index.qmd
    - TODO.md
    - part: enviroment/overview.qmd
      chapters:
        - enviroment/setup.qmd
        - enviroment/rstudio.qmd
        - enviroment/quarto.qmd
        - enviroment/markdown.qmd
        - enviroment/latex.qmd

    - part: r-lang/overview.qmd
      chapters:
        - r-lang/basic.qmd
        - r-lang/advanced.qmd

    - part: minizinc/overview.qmd
      chapters:
        - minizinc/basic.qmd
        - minizinc/advanced.qmd

    - part: python-lang/overview.qmd
      chapters:
        - python-lang/basic.qmd
        - python-lang/advanced.qmd

    - part: linear/overview.qmd
      chapters:
        - linear/algebra.qmd
        - linear/graphical-solution.qmd
        - linear/sensetivity.qmd
        - linear/dual.qmd
        - linear/simplex.qmd
        - linear/simplex-spec.qmd
        - linear/simplex-ext.qmd
        - linear/integer.qmd
        - linear/transport.qmd
        - linear/network.qmd

    - part: nonlinear/overview.qmd
      chapters:
        - nonlinear/unconstrained/analytical-one.qmd
        - nonlinear/unconstrained/analytical-many.qmd
        - nonlinear/constrained/analytical-one.qmd
        - nonlinear/constrained/analytical-many.qmd

    - part: combinatorial/overview.qmd
      chapters:
        - combinatorial/graph-theory.qmd
        - combinatorial/problems/constraint-satisfy.qmd
        - combinatorial/problems/optimal-facility-location.qmd
        - combinatorial/problems/network-design.qmd
        - combinatorial/problems/shortest-path.qmd
        - combinatorial/problems/knapsack.qmd
        - combinatorial/problems/bin-packing.qmd
        - combinatorial/problems/minimum-spanning-tree.qmd
        - combinatorial/problems/travelling-salesman.qmd
        - combinatorial/algorithm/dijkstra.qmd
        - combinatorial/algorithm/branch-and-bound.qmd
        - combinatorial/algorithm/dynamic-programming.qmd
        - combinatorial/algorithm/backtracking.qmd

    - part: game-theory/overview.qmd
      chapters:
        - game-theory/matrix.qmd

    - part: multi-objective/overview.qmd

    - part: "Лабораторные работы"
      chapters:
        - lab/1/intro.qmd
        - lab/2/linear.qmd
        - lab/5/constraint.qmd

    - part: "Проверочные работы"
      chapters:
        - exam/1/intro.qmd
        - exam/2/linear.qmd

    - references.qmd


  appendices:
    - part: "Язык программирования R"
      chapters:
        - r-tools/basic.qmd
        - r-tools/renv.qmd
        - r-tools/plotly.qmd
        - r-tools/ggplot2.qmd
        - r-tools/tibble.qmd
        - r-tools/purrr.qmd
        - r-tools/tidyr.qmd
        - r-tools/lpsolve.qmd
    - part: "Язык программирования Python"
      chapters:
        - python-tools/minizinc.qmd
