format:
  pdf:
    use-rsvg-convert: true
    documentclass: scrbook
    classoption: [twoside=false]
    papersize: a4
    colorlinks: true
    fig-width: 5
    fig-height: 4
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Noto Sans Mono Black
    top-level-division: chapter
