project:
  type: book
  pre-render:
    - scripts/ensure_profile.R

profile:
  group:
    - [full, student, practice, exam, test]
    - [dev, prod]
    - [html, pdf, pdf-class]

book:
  title: "Исследование операций"
  author: "Афоненко Анатолий"
  date: today
  date-format: long

  repo-url: "https://github.com/AfonenkoA/Operations-Research"
  repo-actions: [issue, source]
  repo-branch: master

lang: ru

bibliography:
  - combinatorial/ref.bib
  - practice/basic-model/ref.bib
  - practice/linear/simplex/ref.bib
  - practice/linear/graphical/ref.bib
  - practice/linear/algebra/ref.bib
  - evolutionary/ref.bib
  - minizinc/ref.bib
  - enviroment/ref.bib
  - game-theory/ref.bib
  - lab/ref.bib
  - lab/alghorithm/linear/algebra/ref.bib
  - lab/extra/constraint/ref.bib
  - multi-objective/ref.bib
  - linear/ref.bib
  - python/lang/ref.bib
  - r/lang/ref.bib
  - r/tools/ref.bib
  - nonlinear/ref.bib
  - nonlinear/unconstrained/ref.bib
  - global-ref.bib


csl: gost-r-7-0-5-2008-numeric.csl

engine: knitr
