project:
  type: book

book:
  title: "Operations Research"
  author: "Афоненко Анатолий"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - enviroment/rstudio.qmd
    - enviroment/markdown.qmd
    - enviroment/latex.qmd
    - r-lang/basic.qmd
    - r-lang/advanced.qmd
    - r-tools/figure-plot.qmd
    - linear/linear-algebra.qmd
    - linear/linear-intro.qmd
    - lab1/intro.qmd
    - lab2/linear.qmd

bibliography: references.bib

freeze: auto

format:
  html:
    theme: cosmo

editor: visual
