format:
  pdf:
    latex-auto-install: false
    use-rsvg-convert: true
    documentclass: scrartcl
    fontsize: 11pt
    papersize: a4
    colorlinks: true
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Noto Sans Mono Black
    keep-tex: true
#    geometry:
#     - showframe
