execute:
  freeze: auto
  cache: true

format:
  pdf:
    use-rsvg-convert: true
    documentclass: scrbook
    fontsize: 11pt
    papersize: a4
    colorlinks: true
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Noto Sans Mono Black
