# Язык разметки LaTeX

Для оформления уравнений и формул в рабочих блокнотах Quarto используется общепринятый стандарт разметки математических выражений LaTeX.

+------------------------+------------------------------+
| LaTeX                  | Результат                    |
+========================+==============================+
| ``` markdown           | формула в тексте: $E=mc^{2}$ |
| $\cos{x}$              |                              |
| ```                    |                              |
+------------------------+------------------------------+
| ``` markdown           | отдельный блок формул:       |
| отдельный блок формул: |                              |
|                        | $$E = mc^{2}$$               |
| $$E = mc^{2}$$         |                              |
| ```                    |                              |
+------------------------+------------------------------+

<https://www.overleaf.com/learn/latex/Mathematical_expressions>

## Специальные символы

+--------------+------------+--------------+------------+----------------+---------------+
| Строчная     |            | Прописная    |            | Альтернативная |               |
+==============+============+==============+============+================+===============+
| ``` markdown | $\alpha$   | ``` markdown | $A$        |                |               |
| $\alpha$     |            | $A$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\beta$    | ``` markdown | $B$        |                |               |
| $\beta$      |            | $B$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\gamma$   | ``` markdown | $\Gamma$   |                |               |
| $\gamma$     |            | $\Gamma$     |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\delta$   | ``` markdown | $\Delta$   |                |               |
| $\delta$     |            | $\Delta$     |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\epsilon$ | ``` markdown | $E$        | ``` markdown   | $\varepsilon$ |
| $\epsilon$   |            | $E$          |            | $\varepsilon$  |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\zeta$    | ``` markdown | $Z$        |                |               |
| $\zeta$      |            | $Z$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\eta$     | ``` markdown | $H$        |                |               |
| $\eta$       |            | $H$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\theta$   | ``` markdown | $\Theta$   | ``` markdown   | $\vartheta$   |
| $\theta$     |            | $\Theta$     |            | $\vartheta$    |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\zeta$    | ``` markdown | $Z$        |                |               |
| $\zeta$      |            | $Z$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\kappa$   | ``` markdown | $K$        | ``` markdown   | $\varkappa$   |
| $\kappa$     |            | $K$          |            | $\varkappa$    |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\lambda$  | ``` markdown | $\Lambda$  |                |               |
| $\lambda$    |            | $Lambda$     |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\mu$      | ``` markdown | $M$        |                |               |
| $\mu$        |            | $M$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\nu$      | ``` markdown | $N$        |                |               |
| $\nu$        |            | $N$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\xi$      | ``` markdown | $\Xi$      |                |               |
| $\xi$        |            | $\Xi$        |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\omicron$ | ``` markdown | $O$        |                |               |
| $\omicron$   |            | $O$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\pi$      | ``` markdown | $\Pi$      | ``` markdown   | $\varpi$      |
| $\pi$        |            | $\Pi$        |            | $\varpi$       |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\rho$     | ``` markdown | $P$        | ``` markdown   | $\varrho$     |
| $\rho$       |            | $P$          |            | $\varrho$      |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\sigma$   | ``` markdown | $\Sigma$   | ``` markdown   | $\varsigma$   |
| $\sigma$     |            | $\Sigma$     |            | $\varsigma$    |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\tau$     | ``` markdown | $T$        |                |               |
| $\tau$       |            | $T$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\upsilon$ | ``` markdown | $\Upsilon$ |                |               |
| $\upsilon$   |            | $\Upsilon$   |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\phi$     | ``` markdown | $\Phi$     | ``` markdown   | $\varphi$     |
| $\phi$       |            | $\Phi$       |            | $\varphi$      |               |
| ```          |            | ```          |            | ```            |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\chi$     | ``` markdown | $X$        |                |               |
| $\chi$       |            | $X$          |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\psi$     | ``` markdown | $\Psi$     |                |               |
| $\psi$       |            | $\Psi$       |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+
| ``` markdown | $\omega$   | ``` markdown | $\Omega$   |                |               |
| $\omega$     |            | $\Omega$     |            |                |               |
| ```          |            | ```          |            |                |               |
+--------------+------------+--------------+------------+----------------+---------------+

: Греческие символы

## Стрелки

+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\leftarrow$       | ``` markdown         | $\Leftarrow$         |
| $\leftarrow$       |                    | $\Leftarrow$         |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\rightarrow$      | ``` markdown         | $\Rightarrow$        |
| $\rightarrow$      |                    | $\rightarrow$        |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\leftrightarrow$  | ``` markdown         | $\rightleftharpoons$ |
| $\leftrightarrow$  |                    | $\rightleftharpoons$ |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\uparrow$         | ``` markdown         | $\downarrow$         |
| $\uparrow$         |                    | $\downarrow$         |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\Uparrow$         | ``` markdown         | $\Downarrow$         |
| $\Uparrow$         |                    | $\Downarrow$         |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\Leftrightarrow$  | ``` markdown         | $\Updownarrow$       |
| $\Leftrightarrow$  |                    | $\Updownarrow$       |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\mapsto$          | ``` markdown         | $\longmapsto$        |
| $\mapsto$          |                    | $\longmapsto$        |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\nearrow$         | ``` markdown         | $\searrow$           |
| $\nearrow$         |                    | $\searrow$           |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\swarrow$         | ``` markdown         | $\nwarrow$           |
| $\swarrow$         |                    | $\nwarrow$           |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\leftharpoonup$   | ``` markdown         | $\rightharpoonup$    |
| $\leftharpoonup$   |                    | $\rightharpoonup$    |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+
| ``` markdown       | $\leftharpoondown$ | ``` markdown         | $\rightharpoondown$  |
| $\leftharpoondown$ |                    | $\rightharpoondown$  |                      |
| ```                |                    | ```                  |                      |
+--------------------+--------------------+----------------------+----------------------+

: Стрелки

## Бинарные операторы и символы отношения

+--------------+-------------+--------------+-------------+
| ``` markdown | $\times$    | ``` markdown | $\cdot$     |
| $\times$     |             | $\cdot$      |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\div$      | ``` markdown | $\cap$      |
| $\div$       |             | $\cap$       |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\cup$      | ``` markdown | $\neq$      |
| $\cup$       |             | $\neq$       |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\leq$      | ``` markdown | $\geq$      |
| $\leq$       |             | $\geq$       |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\in$       | ``` markdown | $\perp$     |
| $\in$        |             | $\perp$      |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\notin$    | ``` markdown | $\subset$   |
| $\notin$     |             | $\subset$    |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\simeq$    | ``` markdown | $\approx$   |
| $\simeq$     |             | $\approx$    |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\wedge$    | ``` markdown | $\vee$      |
| $\wedge$     |             | $\vee$       |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\oplus$    | ``` markdown | $\otimes$   |
| $\oplus$     |             | $\otimes$    |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\Box$      | ``` markdown | $\boxtimes$ |
| $\Box$       |             | $\boxtimes$  |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+
| ``` markdown | $\equiv$    | ``` markdown | $\cong$     |
| $\equiv$     |             | $\cong$      |             |
| ```          |             | ```          |             |
+--------------+-------------+--------------+-------------+

: Операторы

## Прочие символы

## Выделяемые функции

+-------------------+---------------------------------------------------------------------+
| LaTeX             | Результат                                                           |
+===================+=====================================================================+
| ``` markdown      | $\cos{x}$                                                           |
| $\cos{x}$         |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\sin{x}$                                                           |
| $\sin{x}$         |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\csc{x}$                                                           |
| $\csc{x}$         |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\exp\biggl(\, \sum_{n=1}^{10} \frac{1}{n} \biggr)$                 |
| $\exp{x}$         |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\min_{\forall s \in S_j} q_k(s)$                                   |
| $\min_{sub} expr$ |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\gcd{144,12}$                                                      |
| $\gcd$            |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $A(n) \in \Theta(n^{\log_b a}) = \Theta(n^{\log_2 2} ) = \Theta(n)$ |
| $\log_b n$        |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+
| ``` markdown      | $\sup_{x>0}f(x)$                                                    |
| $\sup_i f$        |                                                                     |
| ```               |                                                                     |
+-------------------+---------------------------------------------------------------------+

: Функции

## Скобки

## Матрицы

+-------------------+-----------------------------------------+-----------------------------------------+
| Тип               | LaTeX                                   | Результат                               |
+===================+=========================================+=========================================+
| Обычная           | ``` markdown                            | $$                                      |
|                   | $$                                      | \begin{matrix}                          |
|                   | \begin{matrix}                          | 1 & 2 & 3 \\                            |
|                   | 1 & 2 & 3 \\                            | 4 & 5 & 6 \\                            |
|                   | 4 & 5 & 6 \\                            | 7 & 8 & 9                               |
|                   | 7 & 8 & 9                               | \end{matrix}                            |
|                   | \end{matrix}                            | $$                                      |
|                   | $$                                      |                                         |
|                   | ```                                     |                                         |
+-------------------+-----------------------------------------+-----------------------------------------+
| Квадратные скобки | ``` markdown                            | $$ M =                                  |
|                   | $$ M =                                  | \begin{bmatrix}                         |
|                   | \begin{bmatrix}                         | \frac{5}{6} & \frac{1}{6} & 0 \\        |
|                   | \frac{5}{6} & \frac{1}{6} & 0 \\        | \frac{5}{6} & 0 & \frac{1}{6} \\        |
|                   | \frac{5}{6} & 0 & \frac{1}{6} \\        | 0 & \frac{5}{6} & \frac{1}{6}           |
|                   | 0 & \frac{5}{6} & \frac{1}{6}           | \end{bmatrix}                           |
|                   | \end{bmatrix}                           | $$                                      |
|                   | $$                                      |                                         |
|                   | ```                                     |                                         |
+-------------------+-----------------------------------------+-----------------------------------------+
| Выражение         | ``` markdown                            | $$                                      |
|                   | $$                                      | M =                                     |
|                   | M =                                     | \begin{bmatrix}                         |
|                   | \begin{bmatrix}                         | 1 & 0 \\                                |
|                   | 1 & 0 \\                                | 0 & 1                                   |
|                   | 0 & 1                                   | \end{bmatrix}                           |
|                   | \end{bmatrix}                           | \begin{bmatrix}                         |
|                   | \begin{bmatrix}                         | 1 & 0 \\                                |
|                   | 1 & 0 \\                                | 0 & 1                                   |
|                   | 0 & 1                                   | \end{bmatrix}                           |
|                   | \end{bmatrix}                           | $$                                      |
|                   | $$                                      |                                         |
|                   | ```                                     |                                         |
+-------------------+-----------------------------------------+-----------------------------------------+
| Круглые скобки    | ``` markdown                            | $$                                      |
|                   | $$                                      | M =                                     |
|                   | M =                                     | \begin{pmatrix}                         |
|                   | \begin{pmatrix}                         | 1 & 0 \\                                |
|                   | 1 & 0 \\                                | 0 & 1                                   |
|                   | 0 & 1                                   | \end{pmatrix}                           |
|                   | \end{pmatrix}                           | \begin{pmatrix}                         |
|                   | \begin{pmatrix}                         | 1 & 0 \\                                |
|                   | 1 & 0 \\                                | 0 & 1                                   |
|                   | 0 & 1                                   | \end{pmatrix}                           |
|                   | \end{pmatrix}                           | $$                                      |
|                   | $$                                      |                                         |
|                   | ```                                     |                                         |
+-------------------+-----------------------------------------+-----------------------------------------+
| Общий вид         | ``` markdown                            | $$                                      |
|                   | $$                                      | A_{m,n} =                               |
|                   | A_{m,n} =                               | \begin{pmatrix}                         |
|                   | \begin{pmatrix}                         | a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\ |
|                   | a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\ | a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\ |
|                   | a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\ | \vdots & \vdots & \ddots & \vdots \\    |
|                   | \vdots & \vdots & \ddots & \vdots \\    | a_{m,1} & a_{m,2} & \cdots & a_{m,n}    |
|                   | a_{m,1} & a_{m,2} & \cdots & a_{m,n}    | \end{pmatrix}                           |
|                   | \end{pmatrix}                           | $$                                      |
|                   | $$                                      |                                         |
|                   | ```                                     |                                         |
+-------------------+-----------------------------------------+-----------------------------------------+

: Матрицы

## Большие операторы

## Примеры

$$
x^{2 \alpha} - 1 = y_{ij} + y_{ij}
$$

$$
(a^n)^{r+s} = a^{nr+ns}
$$

$$
\sum_{i=1}^{\infty} \frac{1}{n^s} = \prod_p \frac{1}{1 - p^{-s}}
$$

$$
\begin{array}{*{20}c}   {x = \frac{{ - b \pm \sqrt {b^2  - 4ac} }}{{2a}}} & {{\rm{when}}} & {ax^2  + bx + c = 0}  \\\end{array}
$$

$$
x^2  + x\left( {a + b} \right) + ab = \left( {x + a} \right)\left( {x + b} \right)
$$

$$
\log _b \left( x \right) = \log _b \left( c \right)\log _c \left( x \right) = \frac{{\log _c \left( x \right)}}{{\log _c \left( b \right)}}
$$

$$
\frac{d}{{dx}}b^x  = b^x \ln \left( b \right)
$$

$$
\int {\sec (ax)} dx = \frac{1}{a}\ln \left| {\tan \left( {\frac{{ax}}{2} + \frac{\pi }{4}} \right)} \right| + c
$$

$$
\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}
$$

$$
y(x,t) = \sum\limits_n {A_n \cos (\omega _n t + \delta _n )\sin (k_n x)}
$$
