---
engine: knitr
---

# Теория игр {#sec-game-theory-overview}

## Форма представления игры {#sec-game-theory-overview-representation}

<!--Шиловская с 16-->

### Развёрнутая {#sec-game-theory-overview-representation-tree}

В данной форме задаются:

-   порядок ходов
-   альтернативы (выборы), доступные игроку, когда подходит очередь его хода
-   информация, доступная игроку на каждом из ходов
-   выигрыши игроков как функции выбранных ходов

Игру представляют в виде дерева решений, где вершины соответствуют ситуациям выбора игроками своей стратегии; каждому игроку отделяется уровень вершин; результат игры записан в конечных вершинах.

```{mermaid}
graph TB;
    A((1)) -- A -->B((2))
    A -- B --> C((2))
    B -- C --> E((5, 3))
    B -- D --> F(("-2,2"))
    C-- C --> H((0,0))
    C -- D --> I((3,5))
```

### Нормальная {#sec-game-theory-overview-representation-normal}

Нормальная форма игры суммирует позиционную игру в трёх элементах:

-   множестве игроков
-   множестве стратегий каждого игрока
-   функции выигрышей, ставящей в соответствие каждому набору стратегий игроков соответствующие выигрыши игроков

Игра может быть описана *платёжной матрицей*: каждая строка матрицы соответствующий отдельному игроку (строки -- возможные стратегии 1-го игрока; столбцы -- стратегии 2-го игрока); элементы матрицы -- платежи, соответствующие решению каждой из сторон о выборе одной из своих стратегий.

|                       |                       |               |
|-----------------------|:---------------------:|:-------------:|
| Стратегии 1-го игрока | Стратегии 2-го игрока |               |
|                       |     1-я стратегия     | 2-я стратегия |
| 1-я стратегия         |          5,3          |     -2,-2     |
| 2-я стратегия         |          0,0          |      3,5      |

## Принцип доминирования {#sec-game-theory-overview-domination}

В теории игр при их исследовании большое значение имеет возможность учёта предпочтения стратегий игроков, которое будет осуществляться с помощью принципа доминирования, который позволяет уменьшить размерность матрицы.

Первый игрок стремится максимизировать свой выигрыш, и ему будет выгодна та стратегия, которая принесёт больший выигрыш. Если элементы некоторой строки платежной матрицы $C$ меньше соответствующих элементов другой строки, то интуитивно ясно, первую можно вычеркнуть. Сформулируем условия доминирования строк и столбцов платежной матрицы, позволяющую уменьшить её размерность.

::: {#def-game-theory-overview-vector-domination}
Вектор $x=(x_1,\dots,x_n)$ доминирует вектор $y=(y_1,\dots,y_n)$, если элементы вектора $x$ больше или равны соответствубщим элементам вектора $y$. То есть $x_i \geq y_i$, для $\forall i=1,\dots n$ и хотя бы одно неравество выполняется как строгое. Про вектор $y$ говорят, что он доминируется вектором $x$.
:::

::: {#def-game-theory-overview-linear-combination}
Линейная комбинация векторов называется выпуклой, если существует такие коэффициенты $k_1,k_2,\dots,k_n,k_l \in [0,1]$ для $i=1, \dots , n$ не равные нулю одновременно, что выполнено условие

$$
k_1 x^1 + k_1 x^2 + \dots + k_n x^n = x
$$
:::

::: {#thm-game-theory-overview-row-domination}
### О доминировании строк

Если в игре с платежной матрицей $C$ какая-либо строка доминируется выпуклой комбинаций остальных строк, то на будет входить с нулевой вероятностью в оптимальную смешанную стратегию первого игрока и её можно вычеркнуть.
:::

::: {#cor-game-theory-overview-row-domination}
1.  Если в матрице существуют несколько одинаковых строк, то все, кроме одной, можно вычеркнуть, и они будут входить с нулевой вероятностью в оптимальную смешанную стратегию первого игрока.
2.  Если какая-либо строка доминируется другой строкой, то меньшую можно вычеркнуть.
:::

::: {#thm-game-theory-overview-col-domination}
### О доминировании столбцов

Если в игре с платёжной матрицей $C$ какой-либо столбец доминирует выпуклую комбинацию остальных столбцов, о он будет входить с нулевой вероятностью в оптимальную смешанную стратегию второго игрока и его можно вычеркнуть.
:::

::: {#exm-game-theory-overview-domination}
Используя принцип доминирования найти оптимальную стратегию

$$
C = 
\begin{pmatrix}
2 & 0 & 1 & 4 \\
1 & 2 & 5 & 3 \\
4 & 1 & 3 & 2
\end{pmatrix}
$$
:::

::: {#sol-game-theory-overview-domination}
Третий и чертвеёртный столбцы доминируют над вторым, поэтому, в соответствии с утверждением о доминировании столбцов, их можно вычеркнуть (они будут входить в нулевой вероятностью в смешанную стратегию **второго игрока**). Получаем

$$
C = 
\begin{pmatrix}
2 & 0 \\
1 & 2 \\
4 & 1
\end{pmatrix}
$$

Из оставшихся трёх строк и двух столбцов можно вычеркнуть первую строку и так как она доминируется третьей строкой. Таким образом, получаем игру с платежной матрицей $2 \times 2: \big(\begin{smallmatrix} 1 & 2\\ 4 & 1 \end{smallmatrix}\big)$, которая решается просто.
:::

<!--В. П. Невежин -->

## Решение в чистых стратегиях {#sec-game-theory-overview-solution}

<!--Шиловская с 17 и Таха с 560-->

Каждый игрок в конфликтной ситуации старается выбрать наиболее выгодную для себя стратегию. 1-й игрок, очевидно, стремится выбрать стратегию, максимизирующую его выигрыш, а 2-й игрок выбирает стратегию, минимизирующую проигрыш. Чтобы определить рациональные границы наибольшего выигрыша и наименьшего проигрыша, вводят понятие ниженй и верхней чистой цены игры.

::: {#def-game-theory-overview-solution-low-price}
Нижней чистой ценой игры (максимином) называют число $\alpha$, которое определяется по формуле

$$
\alpha = \max_i \min_j a_{ij}
$$
:::

::: {#def-game-theory-overview-solution-top-price}
Верхней чистой ценой игры называют число $\beta$, которое определяется по формуле

$$
\beta = \min_j \max_i a_{ij}
$$
:::

::: {#exm-game-theory-overview-solution}
Две компании $A$ и $B$ продают два вида лекарств против гриппа. Компания $A$ рекламирует продукцию на радио $A$ рекламирует продукцию на радио ($A_1$), телевидении ($A_2$) и в газетах ($A_3$). Компания $B$ в дополнении к использованию радио ($B_1$), телевидения ($B_2$) и газет ($B_3$) рассылает по почте брошюры ($B_4$). В зависимости от умения и интенсивности проведения рекламной кампании, каждая из компаний может привлечь на свою сторону часть клиентов конкурирующей компании. Приведенная ниже матрица характеризует процент клиентов, привлеченных или потерянных компанией $A$.

|                    |       |       |       |       |                |
|-------------------:|:-----:|:-----:|:-----:|:-----:|:---------------|
|                    | $B_1$ | $B_2$ | $B_3$ | $B_4$ | Минимумы строк |
|              $A_1$ |   8   |  -2   |   9   |  -3   | -3             |
|              $A_2$ |   6   | **5** |   6   |   8   | **5**          |
|              $A_3$ |  -2   |   4   |  -9   |   5   | -9             |
| Максимумы столбцов |   8   | **5** |   9   |   8   |                |
:::

::: {#sol-game-theory-overview-solution}
Решение игры основано на обеспечении *наилучшего* результата из *наихудших* для каждого игрока. Если компания $A$ выберет стратегию $A_1$, то, независимо от того, что предпринимает компания $B$, наихудшим результатом является потеря компанией $A$ 3% рынка в пользу компании $B$. Это определяется минимумом элементов первой строки матрицы платежей. Аналогично при выборе стратегии $A_2$ наихудшем исходом для компании $A$ является увеличение рынка на 5%, за счёт компании $B$. Наконец, наихудшим исходом при выборе стратегии $A_3$ является потеря компанией $A$ 9% рынка в пользу компании $B$. Эти результаты содержатся в столбце "Минимумы строк". Чтобы достичь наилучшего результата из наихудших, компания $A$ выбирает стратегию $A_2$, так как она соответствует наибольшему элементу столбца "Минимумы строк".

Рассмотрим теперь стратегии компании $B$. Так как элементы матрицы являются платежами компании $A$, критерий *наилучшего результата* из *наихудших* для компании $B$ соответствует выбору минимаксного значения. В результате приходим к выводу, что выбором компании $B$ является стратегия $B_2$.

Оптимальным решением в игре является выбор стратегий $A_2$ и $B_2$, т.е. обеим компаниям следует проводить рекламу на телевидении. При этом выигрыш будет в пользу компании $A$, так как её рынок увеличится на 5%. В этом случае говорят, что цена игры равна 5% и что компании $A$ и $B$ используют стратегии, соответствующие **седловой точке**.

Решение, соответствующее седловой точке, гарантирует, что ни одной компании нет смысла пытаться выбрать другую стратегию. Действительно, если компания $B$ переходит к другой стратегии ($B_1$, $B_3$ или $B_4$), то компания $A$ может сохранить свой выбор стратегии $A_2$, что приведёт к большей потере рынка компанией $B$ (6 или 8%). По тем же причинам компании $A$ нет резона использовать другую стратегию, ибо, если она применит, например стратегию $A_3$, то компания $B$ может использовать свою стратегию $B_3$ и увеличить свой рынок на 9%. Аналогичные выводы имеют место, если компания $A$ будет использовать стратегию $A_1$.
:::

## Игры с природой {#sec-game-theory-overview-nature}

В игре с природой осознанно действует только один игрок, а именно лицо, принимающее решение.

<!--Шиловская-->

::: {#exm-game-theory-overview-nature}
Инвестор действует в условиях информационной непрозрачности и неопределенности на рынке жилья, и это приводит к потере доходности. Чтобы преодолеть неопределённость и повысить доходность инвестиций, необходимо учитывать риски. Итак, инвестор принимает решения о строительстве жилья определенного типа в заранее определённом районе (множество участков для застройки определяется градостроительными решениями, стоимостью земли и другими факторами). Принимая $i$-е решение, инвестор ожидает получить доход в размере $q_{ij}$, если на рынке жилья в момент завершения строительства реализуется $j$-я ситуация. Множество возможных ситуаций на рынке формализуется на основе ретроспективных статистических данных. Матрица, составленная из $q_{ij}, Q={(q_{ij})}_{m\times n}$ называется *матрицей доходов*.

На основе имеющих статистических данных получена следующая матрица доходов:

$$
Q = 
\begin{pmatrix}
2 & 1 & 0 & 1 \\
2 & 3 & 4 & 0 \\
1 & 2 & 1 & 1 \\
4 & 3 & 0 & 0
\end{pmatrix}
$$
:::

### Критерий Лапласса {#sec-game-theory-overview-representation-nature-laplace}

<!--Невежин-->

Данный критерий опирается на "принцип недостаточного основания" Лапласа, согласно которому все состояния природы $S_j, j=1,\dots,m$ полагаются равновероятными $q_j=\frac{1}{n}$. Если в исходной задаче матрица представлена матрицей выйгрышей, то для выбора оптимальной стратегии $i$ выбирают максимальное значение среди предварительно вычисленных по строкам матрицы средних арифметических значений, дающих наиболее ожидаемый выигрыш

$$
\max_{i} \frac{1}{m} \sum_{j=1}^n {q_{ij}}
$$

Соответственно для примера

$$
\max {
\frac{1}{4}
\begin{bmatrix}
2+1+0+1 = 4\\
2+3+4+0 = 9\\
1+2+1+1 = 5\\
4+3+0+0 = 7
\end{bmatrix}
} = 
\max{(1, \frac{9}{4},\frac{5}{4},\frac{7}{4})}
$$

Таким образом выбираем вторую стратегию

### Критерий Вальда {#sec-game-theory-overview-representation-nature-wald}

Критерий Вальда, который часто называют минимаксным или максиминным критерием, опирается на принцип наибольшей осторожности и основывается на выборе наилучшей из наихудших стратегий $i$.

Согласно ему игра с природой ведётся как игра с разумным, причём агрессивным противником, делающим всё для того, чтобы помешать другому игроку достигнуть успеха. Оптимальной считается стратегия, при которой гарантируется выигрыш в любом случае не меньший, чем "нижняя цена игры с природой".

Если в исходной игре результат представляет выигрыш лица, принимающего решение, то при выборе оптимальной стратегии используемый *максиминный критерий*:

$$
Z = \max_i \min_j q_{ij}
$$

Соответственно для примера

$$
\max {
\frac{1}{4}
\begin{bmatrix}
\min{(2,1,0,1)} = 0\\
\min{(2,3,4,0)} = 0\\
\min{(1,2,1,1)} = 1\\
\min{(4,3,0,0)} = 0
\end{bmatrix}
} = 
\max{(0,0,1,0)}
$$ В таком случае выбираем 3-ю стратегию.
