---
editor: 
  markdown: 
    wrap: 72
---

# Нелинейное программирование {#sec-lab-alghorithm-nonlinear}

## Теория

Пример анализа алгоритма

Процедура анализа. Для всех методов требуемых в условии

1.  Найти минимум функции простым вызовом метода.
2.  С определить количество вычислений функции.
3.  С помощью функций trace\_\* найти путь поиска решения
4.  Построить график поиска решения с точками, в которых была вычислена
    функция
5.  Построить график поиска решения с градиентом.

## Задачи

::: {#exr-lab-alghoritm-basic-one-dim}
### Одномерная минимизация

$$
\frac{11}{1+\mathrm{e}^{-x}}+7 \cos{(3x)} + x^2 - 1
$$

@sec-r-tools-stats-optimize

optimx

Conjugated Gradient Quasi newton

1.  Найти минимум функции
2.  Построить график, выделить точку минимума
:::

### Неограниченная

$$
7x^2+27xy+9y^2+8\exp{\bigg[-\bigg(\frac{x^2}{3}-\frac{(y+3)^2}{5}\bigg)\bigg]}+9\exp{\bigg[-\bigg(\frac{(x-1)^2}{5}+\frac{(y-2)^2}{2}\bigg)\bigg]}
$$

1.  Применить @sec-r-tools-solver-nonlinear-nloptr-nelder-mead и
    @sec-r-tools-solver-nonlinear-nloptr-praxis
2.  Применить @sec-r-tools-solver-nonlinear-nloptr-bfgs и
    @sec-r-tools-solver-nonlinear-nloptr-newton

### Минимизация с ограничениями

Решить предыдущий пример с помощью при ограничениях

$$
\begin{aligned}
\frac{x^2}{10}+\frac{y^2}{3}-\frac{xy}{5} \le 6 \\
\frac{x^2}{3}+\frac{y^2}{104}+\frac{xy}{5} \le 3
\end{aligned}
$$

Изобразить область ограничений линиями поверх контурного графика

cobyla, mma

Определим простую функцию $x^2 - \sqrt{2} x + 1$. Её минимум очевиден
$M=(\frac{1}{\sqrt{2}},\frac{1}{2})$

```{{r}}
f <- \(x) x^2 - sqrt(2)*x + 1
```

plot_ly

Комбинированный метод золотого сечения и обратных парабол method =
c("Brent

Аргументами interval или lower, upper задаётся область поиска. Аргумент
maximum отвечает за цель оптимизации.

```{{r}}
optimise(f, c(-5,5))
```

Важный параметр tol, задаёт точность, с которой будет найден оптимум.
Сравним с аналитическим решением разные параметры точности.

```{{r}}
sapply(10^c(-(1:10)),\(t) list(tolerance=t,result=sprintf('%.10f',optimise(f,c(-5,5),tol=t)$minimum ))) |> t()

sprintf('%.10f',1/sqrt(2))
```

## Методы без вычисления производных

1.  Не сходимость если ограничения совпадают
2.  Не локализация, если два экстремума

В связи с особенностью одномерного случая введём для рассмотрения две
функции: выпуклую и невыпуклую

### Метод золотого сечения

Алгоритм брента.

```{r}
# optimise()
```

1.  Расходимость при невыпуклой функции

Пауэл и золотое сечение

### Горбы и ямы

Найти безусловный минимум функции двух переменных, провести сравнение из
предложенных методов. Графики, анимации, итерации. Нелдермид локальной
вариации LBFGS

### Ограничения

Решить задачу с ограничениями

### Овраг

$$
(9x+8y-5)^4 + (5x+2y-1)^4
$$

Nelder-Mead, Newton

### Много переменных

Провести анализ для всех предложенных функций (n=20,50,200)
$$F=(\sum_{i=1}^N{L_ix_i}-b)^2$$ Вектор коэффициентов Li сгенерировать
случайным образом

### Условия не писаны

Уровень 3 попробовать барьерные функиции

Найти условно минимум функции двух переменных, с ограничениями.
Использовать доступные методы, провести сравнение.

Свести задачу условной оптимизации к безусловной выбрав барьерные
функции. Там где надо применить штрафные или барьерные функции
обязательно подробная инструкция
