# Линейное программирование. Модели {#sec-practice-linear-model}

:::: {.content-hidden when-profile="practice"}
::: {.callout-important title="Состояние разработки"}
Требуется доработка
:::
::::

::::: {.content-hidden when-profile="practice"}
## Темы {#sec-practice-linear-model-topics}

Привести в стандартную форму. Построить модель текстовой задаче. Сформулировать двойственную задачу

::: {#exm-practice-linear-model}
### Примерчик

Задание
:::

::: {#sol-practice-linear-model}
Решение
:::
:::::

::::: {.content-hidden when-profile="student" when-profile="practice" unless-meta="convert-to-linear.select"}
:::: {#exr-practice-linear-model-convert-to-linear}
## Линейная модель

Минимизировать $z=\max\{|x_1-x_2+3x_3|,|-x_1+3x_2-x_3|\}$, при ограничениях $x_1,x_2,x_3 \geq 0$. Подсказка: представьте, что $z$ это число, которое не меньше, чем аргументы $\max$ и примените свойство модуля $|a|\leq b$ эквивалентна записи $a\leq b$ и $a \geq -b$. Привести к линейной модели.

::: {.callout-note appearance="minimal" title="Оценка"}
0.25
:::

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="practice"}
::::
:::::

:::: {.content-hidden when-profile="student" when-profile="practice"}
::: {#sol-practice-linear-model-convert-to-linear}
{{< lipsum 1 >}}
:::
::::

::::: {.content-hidden when-profile="student" when-profile="practice" unless-meta="standard-form.select"}
:::: {#exr-practice-linear-model-standard-form}
## Красиво?

Привести к задаче максимизации в стандартной форме.

$$
\begin{aligned}
&\mathrm{F}=-2x_1+5x_2-3x_3+x_4 \rightarrow \min \\
&\begin{cases}
2x_1+3x_2+x_3+2x_4 \leq 18, \\
x_1+6x_2+11x_3-x_4 \geq 25, \\
3x_2+2x_3+x_4 \leq -8, \\
x_1,x_2,x_3 \geq 0\\
x_4 \in \mathbb{R}
\end{cases}
\end{aligned}
$$

::: {.callout-note appearance="minimal" title="Оценка"}
0.25
:::

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="practice"}
::::
:::::

:::: {.content-hidden when-profile="student" when-profile="practice"}
::: {#sol-practice-linear-model-standard-form}

Приведём целевую функцию к задаче максимизации следующим образом $\min F(x) = - \max \bigl(-F(x) \bigr)$

$$
F=2x_1-5x_2+3x_3-x_4
$$

Преобразуем 1 и 3 ограничение вводя остаточные переменные $o_i$ @sec-linear-overview-standart-problem-constraint и приводим к неотрицательной правой части

$$
\begin{aligned}
&2x_1+3x_2+x_3+2x_4+o_1=18\\
&-3x_2-2x_3-x_4-o_2=8
\end{aligned}
$$
А ограничение 2 введя избыточную переменную $i_1$ 

$$
x_1+6x_2+11x_3-x_4-i_1=25
$$

Наконец преобразуем свободную переменную $x_4$ @sec-linear-overview-standart-problem-free-variable

$$
\begin{aligned}
&x_4=x_4^--x_4^+\\
&x_4^-,x_4^+\geq0
\end{aligned}
$$

Итоговая формулировка

$$
\begin{aligned}
&F=2x_1-5x_2+3x_3-x_4^-+x_4^+ \rightarrow \max \\
&\begin{cases}
2x_1+3x_2+x_3+2x_4^--2x_4^++o_1=18\\
x_1+6x_2+11x_3-x_4^-+x_4^+-i_1=25\\
-3x_2-2x_3-x_4-o_2=8\\
x_1,x_2,x_3,x_4^-,x_4^+\geq0\\
o_1,o_2,i_1\geq0
\end{cases}
\end{aligned}
$$

:::
::::

::::: {.content-hidden when-profile="student" when-profile="practice" unless-meta="build-model.select"}
:::: {#exr-practice-linear-model-build-model}
## Dolce vita

Активист творческого союза пришёл к выводу, что только одна учёба плохо повлияет на его умственное и физическое развитие. Поэтому он решил распределить всё своё свободное время на неделю 70 часов между учёбой, спортом, организацией мероприятий и тусовками. Он полагает, что тусовки в два раза круче мероприятий и в 1.5 раза лучше, чем спорт, а мероприятия интереснее учёбы в 2 раза. Однако тусовок организуется в два раза меньше, чем мероприятий, а на учёбу придётся тратить не меньше 6 часов в день 6 дней в неделю. Составьте модель, которая позволит активисту получить максимальное удовольствие от жизни.

::: {.callout-note appearance="minimal" title="Оценка"}
0.5
:::

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="practice"}
::::
:::::

:::: {.content-hidden when-profile="student" when-profile="practice"}
::: {#sol-practice-linear-model-build-model}
{{< lipsum 2 >}}
:::
::::

:::::: {.content-hidden when-profile="student" when-profile="practice" unless-meta="dual-problem.select"}
::::: {#exr-practice-linear-model-dual}
## Двойственность

Сформулировать двойственную задачу <!--// Таха 4.4 189-->

::: {layout-ncol="2"}
$$
\begin{aligned}
&\mathrm{F}=-5x_1+2x_2 \rightarrow \max \\
&\begin{cases}
-x_1+x_2 \leq 2, \\
2x_1+3x_2 \leq 5, \\
x_1,x_2 \geq 0
\end{cases}
\end{aligned}
$$

$$
\begin{aligned}
&\mathrm{F}=3x_1+4x_2 \rightarrow \max \\
&\begin{cases}
5x_1+6x_2=7,\\
x_1,x_2 \geq 0
\end{cases}
\end{aligned}
$$
:::

::: {.callout-note appearance="minimal" title="Оценка"}
0.75
:::

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="practice"}
:::::
::::::

:::: {.content-hidden when-profile="student" when-profile="practice"}
::: {#sol-practice-linear-model-dual-problem}

Основываясь на правилах, определённых в @sec-linear-dual-problem получаем:

Первый случай подходит под следующую формулировку

$$
\begin{aligned}
&\max \mathrm{\mathbf{c}}^T\mathrm{\mathbf{x}} \\
&\mathrm{\mathbf{A}} \mathrm{\mathbf{x}} \leq \mathrm{\mathbf{b}} \\
&\mathrm{\mathbf{x}} \geq 0
\end{aligned} 
\longrightarrow
\begin{aligned}
&\min \mathrm{\mathbf{b}}^T\mathrm{\mathbf{y}} \\
&\mathrm{\mathbf{A}}^T \mathrm{\mathbf{y}} \geq \mathrm{\mathbf{c}} \\
&\mathrm{\mathbf{y}} \geq 0
\end{aligned} 
$$

Соответственно двойственная задача

$$
\begin{aligned}
&\min 2y_1+5y_2 \\
&\begin{cases}
-y_1+2y_2 \geq -5 \\
y_1 + 3y_2 \geq 2
\end{cases}
\end{aligned}
$$

Во втором случае, условия равенства $=b_i$ и $x_i \geq 0$ будут преобразованы в $y_i \in \mathbb{R}$ и подходит под следующую типовую формулировку

$$
\begin{aligned}
&\max \mathrm{\mathbf{c}}^T\mathrm{\mathbf{x}} \\
&\mathrm{\mathbf{A}} \mathrm{\mathbf{x}} = \mathrm{\mathbf{b}} \\
&\mathrm{\mathbf{x}} \geq 0
\end{aligned} 
\longrightarrow
\begin{aligned}
&\min \mathrm{\mathbf{b}}^T\mathrm{\mathbf{y}} \\
&\mathrm{\mathbf{A}}^T \mathrm{\mathbf{y}} \geq \mathrm{\mathbf{c}} \\
&\mathrm{\mathbf{y}} \in \mathbb{R}
\end{aligned} 
$$

Соответственно двойственная задача

$$
\begin{aligned}
&\min 7y_1\\
&\begin{cases}
5y_1\geq3\\
6y_1\geq4\\
y_1 \in \mathbb{R}
\end{cases}
\end{aligned}
$$

:::
::::
