# 2. Линейное программирование {#sec-lab-2}

::: {.callout-important title="Состояние разработки"}
Требуется доработка
:::

## Инструкции {#sec-lab-2-instructions}

### Установка

### Теория

::: {#exm-lab-2}
Пример
:::

::: {#sol-lab-2}
Решение примера
:::

## Задания

::::: {#exr-lab-2-simple-graphical-solution}
### Простота и наглядность

$$
\begin{aligned}
&\mathrm{F}=5x_1+4x_2 \rightarrow \max \\
&\begin{cases}
6x_1+4x_2\leq24\\
x_1+2x_2\leq6\\
-x_1+x_2\leq1\\
x_1,x_2\geq0
\end{cases}
\end{aligned}
$$

1.  Построить целевую функцию
2.  Построить прямые, определяющие ограничения
3.  Определить точки пересечения прямых
4.  Определить решение графически.

::: callout-tip
Можно добавлять элементы на график последовательно отображая их @sec-r-tools-plotly-combine.
:::

::: {.callout-note appearance="minimal"}
Уровень 1
:::
:::::

:::: {#exr-lab-2-solver}
### Пакет с пакетами

С помощью пакета @sec-r-tools-lpsolve получить решение задачи. Используйте, @sec-r-tools-lpsolve-lpsolve или @sec-r-tools-lpsolve-lpsolveapi на своё усмотрение.

$$
\begin{aligned}
&\mathrm{F}=3x_1+4x_2+2x_3+5x_4+6x_5+7x_6+8x_7+9x_8+10x_9+11x_{10} \rightarrow \max \\
&\begin{cases}
x_1+2x_2+3x_3+x_4+4x_5+6x_6+7x_8+8x_9+9x_{10} \leq 30\\
2x_1+x_2+2x_3+3x_4+2x_5+3x_6+4x_7+5x_8+x_9+3x_{10}\leq 20\\
3x_1+4x_2+x_3+4x_4+5x_5+2x_6+x_7+3x_8+2x_9+x_{10} \leq 25\\
4x_1+2x_2+5x_3+x_4+2x_5+3x_6+5x_7+6x_8+2x_9+4x_{10} \leq 25\\
x_1+2x_2+5x_3+x_4+2x_5+4x_6+5x_7+x_8+x_9+3x_{10} \leq 18 \\
5x_1+6x_2+x_3+3x_4+4x_5+5x_6+6x_7+7x_8+x_9+2x_{10} \leq 22 \\
2x_1+3x_2+4x_3+x_4+4x_5+3x_6+2x_7+5x_8+7x_9+8x_{10} \leq 19 \\
x_i\geq0,\forall x_i
\end{cases}
\end{aligned}
$$

::: {.callout-note appearance="minimal"}
Уровень 1
:::
::::

:::: {#exr-lab-2-syllabus}
### Учебный план

Для новых специальностей на факультете радиофизики запланировано 3500 учебных часов. Основные разделы подготовки студентов и затраты на разработку приведены ниже.

| Раздел                    | Затраты |
|---------------------------|---------|
| Аэрокосмос                | 3       |
| Физика                    | 1       |
| Микроэлектроника          | 2       |
| Математика                | 1       |
| Компьютерная безопасность | 3       |
| Программирование          | 1       |
| Радиофизика               | 2       |
| Статистика                | 1       |
| Машинное обучение         | 2       |

Соотношение между часами учебных дисциплин должно быть не меньше, чем указано в диаграмме

```{mermaid}
graph LR
    AeroSpace(Аэрокосмос)
    Physics(Физика)
    MicroEl(Микроэлектроника)
    Math(Математика)
    CyberSecurity(Инфобез)
    Programming(Программирование)
    RadioPhysics(Радиофизика)
    Statistics(Статистика)
    MachineLearning(Машинное обучение)

    RadioPhysics -->|2| Math
    RadioPhysics -->|2| Physics
    MachineLearning -->|1| Math
    MachineLearning -->|1| Statistics
    MachineLearning -->|1| Programming
    AeroSpace -->|1| RadioPhysics
    AeroSpace -->|1| Programming
    CyberSecurity -->|2| Programming
    CyberSecurity -->|1| Math
    CyberSecurity -->|1| Physics
    MicroEl -->|2| Programming
    MicroEl -->|1| Physics
```

Согласно положению за период обучения должно быть прочитано часов не менее

| Раздел                    | Часы |
|---------------------------|------|
| Компьютерная безопасность | 400  |
| Аэрокосмос                | 300  |
| Радиофизика               | 300  |
| Машинное обучение         | 400  |
| Микроэлетроника           | 300  |

Определите наиболее выгодное распределение часов (стоимость) для студента и для факультета.

::: {.callout-note appearance="minimal"}
Уровень 2
:::
::::

:::: {#exr-lab-2-part-time-job}
### Работа не волк, а work

Лишенный стипендии студент для поддержания своего финансового уровня должен подрабатывать и получить не менее 700 руб в месяц. У него есть следующие альтернативы

| Работа              | Часов, не менее | Часов, не более | Напряженность | Доход/час |
|---------------------|-----------------|-----------------|---------------|-----------|
| Курьер              | 10              | 20              | 12            | 10        |
| Повар               | 20              | 40              | 8             | 11        |
| Грузчик             | 5               | 60              | 15            | 8         |
| Продавец            | 25              | 70              | 10            | 12        |
| Фриланс разработчик | 20              | 50              | 20            | 30        |

Понятно, что общая напряженность в месяц пропорциональна количеству отработанных часов. Найдите оптимальную занятость студента.

::: {.callout-note appearance="minimal"}
Уровень 2
:::
::::

:::: {#exr-lab-2-diet-planning}
### На всю котлету

Столовая № 8 готовит блюда из картошки, овощей, курицы, свинины, крупы. Возможные ежедневные поставки ограничены. Стоимость кг сырья составляет. Минимальный дневной спрос.

| Продукт  | Огр. поставок кг | Стоимость/кг |
|----------|------------------|--------------|
| Овощи    | 50               | 3            |
| Крупа    | 30               | 1            |
| Мясо     | 10               | 12           |
| Макароны | 20               | 5            |

: Базовые продукты

| Блюдо   | Состав             | Пропорция | Дневное потребление |
|---------|--------------------|-----------|---------------------|
| Супы    | Овощи, Крупа, Мясо | 2:3:1     | 15                  |
| Гарнир  | Овощи, Крупа       | 1:1       | 20                  |
| Горячее | Мясо, Макароны     | 3:2       | 10                  |
| Салаты  | Мясо, Овощи        | 1:8       | 5                   |

: Готовые блюда

Разработайте модель ЛП оптимального производственного плана и потребности в ингредиентах. Как изменится решение, если стоимость блюда, а если измениться ограничение. При какой наименьшей стоимости будет иметь смысл производить. Как существенно повысить прибыль, если есть всего одна возможность.

::: {.callout-note appearance="minimal"}
Уровень 2
:::
::::

:::: {#exr-lab-2-mechanical-kit}
### А что, если болт?

В хозяйственном магазине покупают монтажные наборы из винтов, болтов, гаек и и шайб. Винты поставляют в коробках по 5 кг по цене 110 руб за коробку. Болты поставляют в коробках по 3 кг ценой по 150 руб, гайки в коробках по 3 кг стоимостью 70 руб, а шайбы в коробках по 1 кг ценой 20 руб за коробку. Монтажный набор должен весить не меньше 500 грамм и включать (по весу) не менее 10% винтов и 25% болтов, не не более 15% гаек и 10% шайб. Чтобы пакет был правильно укомплектован, количество болтов не должно превосходить количество гаек и количество шайб. Один болт вести в 10 раз больше гайки и в 50 раз больше шайбы. Создайте модель ЛП для определения оптимального состава монтажного набора и найдите решение. // Таха 2.68 c 83

::: {.callout-note appearance="minimal"}
Уровень 3
:::
::::

:::: {#exr-lab-2-dual-problem}
### Враг в отражении

Решите двойственную к следующей задачу ЛП, а затем найдите оптимальное решение прямой задачи. Даёт ли в этом случае вычислительное преимущество по сравнению с решением прямой задачи ЛП? // 4.11 с 190 Таха

$$
\begin{aligned}
&\mathrm{F}=5x_1+6x_2+3x_3 \rightarrow \min \\
&\begin{cases}
5x_1+5x_2+3x_3 \geq 50,\\
x_1+x_2-x_3 \geq 20, \\
7x_1+6x_2-9x_3 \geq 30, \\
5x_1+5x_2+5x_3 \geq 35, \\
2x_1+4x_2-15x_3 \geq 10, \\
12x_1+10x_2 \geq 90, \\
x_2-10x_3 \geq 20, \\
x_1,x_2,x_3 \geq 0
\end{cases}
\end{aligned}
$$

::: {.callout-note appearance="minimal"}
Уровень 3
:::
::::

::::: {#exr-lab-2-simplex-alghorytm}
### Верный алгоритм

#### Симплекс метод

Реализовать симплекс, считая входные данные "хорошими" (не обрабатывать особые случаи и ошибки).

::: {.callout-note appearance="minimal"}
Уровень 4
:::

#### Двухэтапный метод

Реализовать M-метод или двухэтапный метод.

::: {.callout-note appearance="minimal"}
Уровень 4
:::
:::::

## Разбалловка {#sec-lab-2-scoring}

| Объём работы | Итоговый балл |
|----|----|
| [Симплекс метод](https://dialog.guide/simplex-metod/) — надежный и творческий инструмент для решения проблем. | Не сдано |
| Все задачи уровня 1 | 2 |
| Все задачи уровней 1 и 2 | 3 |
| Все задачи уровней 1, 2 и 3 | 4 |
| Все задачи уровней 2, 3 и 4 | 5 |

: Разбалловка {tbl-lab-2-scoring}

## Проверочная работа

-   Решить графически задачу для двух переменных
-   Привести в стандартную форму
-   Построить модель текстовой задаче
-   Определить, какой из особых случаев реализован
    -   Вырожденность
    -   Альтернативные оптимальные решения
    -   Отсутствие допустимых решений
    -   Неограниченность
-   Графический анализ чувствительности оптимального решения
    -   По коэффициентам целевой функции
    -   По ограничениям
-   Сформулировать двойственную задачу
-   Решить задачу
    -   Симплекс методом
    -   М-Методом
    -   Двухэтапным симплекс методом
