```{r}
#| label: import
#| warning: false
#| message: false
#| include: false 

source('../../util/doc_link.R')
source('../../util/plotly_show.R')
```

# Лабораторная работа 2. Линейное программирование {#sec-lab2}

::: {.callout-important title="Состояние разработки"}
В разработке
:::

## Задания

### Графическое решение

$$
\begin{align*}
&\mathrm{F}=5x_1+4x_2 \rightarrow \max \\
&\begin{cases}
6x_1+4x_2\leq24\\
x_1+2x_2\leq6\\
-x_1+x_2\leq1\\
x_1,x_2\geq0
\end{cases}
\end{align*}
$$

1.  Построить целевую функцию
2.  Построить прямые, определяющие ограничения
3.  Определить точки пересечения прямых
4.  Определить решение графически.

::: callout-tip
Можно добавлять элементы на график последовательно отображая их @sec-r-tools-plotly-combine.
:::

::: {.callout-note appearance="minimal"}
Уровень 1
:::

### Решение через solver

С помощью пакета @sec-r-tools-lpsolve получить решение задачи. Используйте, @sec-r-tools-lpsolve-lpsolve или @sec-r-tools-lpsolve-lpsolveapi на своё усмотрение.

$$
\begin{align*}
&\mathrm{F}=3x_1+4x_2+2x_3+5x_4+6x_5+7x_6+8x_7+9x_8+10x_9+11x_{10} \rightarrow \max \\
&\begin{cases}
x_1+2x_2+3x_3+x_4+4x_5+6x_6+7x_8+8x_9+9x_{10} \leq 30\\
2x_1+x_2+2x_3+3x_4+2x_5+3x_6+4x_7+5x_8+x_9+3x_{10}\leq 20\\
3x_1+4x_2+x_3+4x_4+5x_5+2x_6+x_7+3x_8+2x_9+x_{10} \leq 25\\
4x_1+2x_2+5x_3+x_4+2x_5+3x_6+5x_7+6x_8+2x_9+4x_{10} \leq 25\\
x_1+2x_2+5x_3+x_4+2x_5+4x_6+5x_7+x_8+x_9+3x_{10} \leq 18 \\
5x_1+6x_2+x_3+3x_4+4x_5+5x_6+6x_7+7x_8+x_9+2x_{10} \leq 22 \\
2x_1+3x_2+4x_3+x_4+4x_5+3x_6+2x_7+5x_8+7x_9+8x_{10} \leq 19 \\
x_i\geq0,\forall x_i
\end{cases}
\end{align*}
$$

::: {.callout-note appearance="minimal"}
Уровень 1
:::

### Самостоятельное формулирование и решение по тексту

::: {.callout-note appearance="minimal"}
Уровень 2
:::

### Анализ чувствительности

::: {.callout-note appearance="minimal"}
Уровень 3
:::

#### По ограничениям

#### По целевой функции

### Самостоятельная формулировка большой проблемы

::: {.callout-note appearance="minimal"}
Уровень 3
:::

### Двойственная задача линейного программирования

::: {.callout-note appearance="minimal"}
Уровень 3
:::

просто переформулировать, закинуть в solver и убедится в свойстве, что min прямой совпадают с max обратной.

### Симплекс метод

реализовать симплекс

::: {.callout-note appearance="minimal"}
Уровень 3
:::

### Двухэтапный метод

Реализовать двухэтапный.

::: {.callout-note appearance="minimal"}
Уровень 4
:::

[Оптимизация в датацентре](https://medium.com/@quachmaiboi/optimizing-data-center-operation-part-1-8c21cf4f9378)
