---
params:
  seed-random: 123
---

# Проверочная работа 2. Линейное программирование

## Решить графически

## Привести в стандартную форму

::::: {.content-hidden unless-meta="operations-research.avia-tickets.select"}
:::: {#exr-exam-1-operations-research-avia-tickets}
::: {.callout-note appearance="minimal" title="Оценка"}
2
:::

[`\vspace{3cm}`{=latex}]{.content-visible when-profile="exam"}
::::
:::::

:::: {.content-hidden when-profile="exam"}
::: {#sol-exam-1-operations-research-avia-tickets}
{{< lipsum 2 >}}
:::
::::

## Построить модель

Активист творческого союза пришёл к выводу, что только одна учёба плохо повлияет на его умственное и физическое развитие. Поэтому он решил распределить всё своё свободное время на неделю 70 часов между учёбой, спортом, организацией мероприятий и тусовками. Он полагает, что тусовки в два раза круче мероприятий и в 1.5 раза лучше, чем спорт, а мероприятия интереснее учёбы в 2 раза. Однако тусовок организуется в два раза меньше, чем мероприятий, а на учёбу придётся тратить не меньше 6 часов в день. Составьте модель, которая позволит активисту получить максимальное удовольствие от жизни.

## Определить, какой из особых случаев реализован

### Вырожденность

Таха
-   2.86
-   3.5
-   3.18
-   3.27
-   3.28
-   3.50
-   3.78 про интеграл

### Альтернативные оптимальные решения

### Отсутсвие допустимых решений

## Графический анализ чувствительности оптимального решения

### По коэффициентам целевой функции

### По ограничениям

## Сформулировать двойственную задачу

Запишите двойственную задачу для следу. // Таха 4.4 189

Максимизировать $z=-5x_1+2x_2$ при ограничениях

$$
\begin{align*}
-x_1+x_2 &\leq 2, \\
2x_1+3x_2 &\leq 5, \\
x_1,x_2 &\geq 0
\end{align*}
$$

Максимизировать $z=x_1+x_2$ при ограничениях

$$
\begin{align*}
2x_1+x_2&=5,\\
3x_1-x_2&=6
\end{align*}
$$ при условии, что $x_1,x_2$ свободные переменные.

## Решить задачу двухэтапным методом

Привести графическое решение. Отработать по шагам Минимизировать $z=2x_1+3x_2$ при ограничениях // Таха 4.36 197

$$
\begin{align*}
2x_1+2x_2 &\leq 30,\\
x_1+2x_2 &\geq 10,\\
x_1,x_2 &\geq 0
\end{align*}
$$
