# Задача удовлетворения ограничений

## Числовой пример

$$
\begin{array}{cccccc}
&А&Т&А&К&А\\
+&&У&Д&А&Р\\
&&У&Д&А&Р\\
\hline\\
Н&О&К&А&У&Т
\end{array}
$$

## Судоку

## Игральная доска

Игральная доска состоит из девяти равных полей, расположенных квадратом 3x3. Требуется заполнить каждое поле числом из интервала от 1 до 9 таким образом, чтобы сумма чисел каждой строки, каждого столбца и каждой диагонали была равна 15. Кроме того, числа в каждом поле должны быть уникальны. Решить ЦЛП или minizinc // 9,38 Таха

## Обобщенная задача про вино

Таха 9.3 с 366

Пусть есть 7 полных бутылок вина, 7 бутылок заполненных наполовину, и 7 пустых бутылок. Необходимо распределить 21 бутылку между тремя персонами так, чтобы каждый получил 7 бутылок, но при этом одинаковые количество вина.

Можно решать с помощью ручного сведения к линейной задаче или написать высокоуровневые конструкции, и дать автомату решить.

## Загадка Эйнштейна

1.  На улице стоят пять домов.
2.  Англичанин живёт в красном доме.
3.  У испанца есть собака.
4.  В зелёном доме пьют кофе.
5.  Украинец пьёт чай.
6.  Зелёный дом стоит сразу справа от белого дома.
7.  Тот, кто курит Old Gold, разводит улиток.
8.  В жёлтом доме курят Kool.
9.  В центральном доме пьют молоко.
10. Норвежец живёт в первом доме.
11. Сосед того, кто курит Chesterfield, держит лису.
12. В доме по соседству с тем, в котором держат лошадь, курят Kool.
13. Тот, кто курит Lucky Strike, пьёт апельсиновый сок.
14. Японец курит Parliament.
15. Норвежец живёт рядом с синим домом.

Кто пьёт воду? Кто держит зебру?

В целях ясности следует добавить, что каждый из пяти домов окрашен в свой цвет, а их жители — разных национальностей, владеют разными животными, пьют разные напитки и курят разные марки американских сигарет. Ещё одно замечание: в утверждении 6 справа означает справа относительно вас.
